### ISSUE TITLE
Ensure that TEXMFHOME is fully accessible when checksearch is enabled

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#101]
Currently, when `checksearch` is true, setting `TEXMFHOME`, _etc._ to include extra local material doesn't ensure that the original is still accessible. That requires that a `kpse` lookup of the var value is added.

**Comment by josephwright** [comment]
Hmm, thinking, isn't that what having `;` at the end of the input lists does anyway ...

**Comment by u-fischer** [comment]
Imho yes, but didn't you left out the `;` by purpose in the texmfdir/texinputs setting?
