### ISSUE TITLE
Provide "assertions"

### ISSUE THREAD

**Issue by stone-zeng** [latex3/l3build#102]
Could please consider to add the **Assertions** feature, as in [googletest](https://github.com/google/googletest/blob/master/googletest/docs/primer.md#assertions)? Some macros like `\ASSERTEQ`, `\ASSERTNEQ` help people write unit tests.

In l3kernel, for example, the validity of some test relies on manual check (e.g. see <https://github.com/latex3/latex3/issues/642>). IMHO it's not a robust and efficient way if one has so many test files.

**Comment by josephwright** [comment]
A very large number of tests come down to `\showoutput` or similar, so can't really work that way, but there is no issue in adding some kind of assertion or string tests. Presumably, you are thinking something like
```latex
\str_if_eq:eeTF { <test-case> } { <desired-output> } { \PASS } { \ERROR }
```

**Comment by josephwright** [comment]
(Of course, we don't have `\str_if_eq:nn(TF)` at the level of `regression-test`.)

**Comment by josephwright** [comment]
@stone-zeng  You could put in a PR ;)
