### ISSUE TITLE
Treat ptex as eptex, uptex as euptex in plain

### ISSUE THREAD

**Issue by aminophen** [latex3/l3build#104]
Preparing https://github.com/texjporg/texjporg-testing, I noticed that the latex format does not like "e" (when "eptex" is specified, it starts building eplatex.fmt and fails)

```
checkengines    = checkengines
  or {"ptex", "uptex"}
checkformat  = "latex"
```

but the plain format needs explicit "e" (when "ptex" is specified, it crashes because the regression-test.tex always requires e-TeX)

```
checkengines    = checkengines
  or {"eptex", "euptex"}
checkformat  = "tex"
```

It would be nice if `checkengines` and `stdengine` for plain treat ptex as eptex and uptex as euptex.

**Comment by josephwright** [comment]
One could do testing without `regression-test.tex`, see for example the LaTeX2e test suite (uses it's own `test2e.tex`/`test209.tex`).

One should only need something like
```lua
specialformats = specialformats or  { }
specialformats.tex= specialformats.tex or {
    ptex  = {binary = "eptex"},
    uptex = {binary = "euptex"}
  }
```
which is much the same as we do for LaTeX: I could add to the default, but for plain testing I'm not so sure. (pLaTeX requires e-TeX so it's fine to force there ...).

In some ways I think one could argue this should be 'fixed at the engine end': `pdfetex` became just `pdftex` some years ago ...

**Comment by aminophen** [comment]
> One could do testing without regression-test.tex

Oh, I didn't know that. Also, thanks for the information about `specialformats`. OK, I think this issue is invalid enough, closing.

> one could argue this should be 'fixed at the engine end

Discussion already started some years ago (https://github.com/texjporg/tex-jp-build/issues/32), but still need testing whether e-pTeX is completely (= bug-freely) upward compatible with pTeX. Also, which name (eptex vs ptex) should remain is still controversial ...

**Comment by josephwright** [comment]
We could perhaps make it clear that one can use a different set of macros provided they output the same markers in the log.

On the e-pTeX business: my main concern was that plain is different to LaTeX, and I don't want to set anything up that's misleading. What the Japanese community feel is right for e-pTeX vs pTeX is no an area I can really comment on!

**Comment by aminophen** [comment]
> We could perhaps make it clear that one can use a different set of macros provided they output the same markers in the log.

That would be great! (then I think I can create some test on pTeX vs e-pTeX, which will make the testing much easier for us Japanese...)

**Comment by davidcarlisle** [comment]
I just hit something similar in the `iftex` bundle where most tests use latex or e-engines but I wanted one configuration with a few tests without e-tex so I could test `\ifetex`  I ended up putting

```
ifx\numexpr\undefined
\def\START{\immediate\write-1{START-TEST-LOG}}
\let\zzend\end
\def\end{\immediate\write-1{END-TEST-LOG}\zzend}
\else
\input regression-test
\fi
```

at the top of the test files in https://github.com/latex3/iftex/tree/master/testfiles-plain

I did wonder if I should suggest that `regression-test.tex` defines some really basic setup, perhaps just `\START` `\END` and `\TYPE` if it detects etex isn't present.
