### ISSUE TITLE
Long path in tlg can't be normalized

### ISSUE THREAD

**Issue by stone-zeng** [latex3/l3build#108]
I got some output like the following from [ci for ctex-kit](https://github.com/CTeX-org/ctex-kit/runs/373874499):

```
(/home/runner/work/ctex-kit/ctex-kit/tmp/texlive/texmf-dist/tex/latex/tools/som
edefs.sty
Package: somedefs ....-..-.. v... Toolkit for optional definitions
)
```

and

```
(../2.163.1/work/ctex-kit/ctex-kit/tmp/texlive/texmf-dist/te
x/latex/tools/somedefs.sty
Package: somedefs ....-..-.. v... Toolkit for optional definitions
)
```

When the path takes two lines, it can't be normalized correctly.

`l3build` version: 2019-11-27 (the ci version should be updated to latest as well)

**Comment by josephwright** [comment]
'True': you can fiddle with the max print line setting, but fundamentally we are limited as the log files wrap.

**Comment by blefloch** [comment]
I thought that l3build merged lines that reach the limit with the next
line.  Isn't that the case?

**Comment by josephwright** [comment]
@blefloch WE do our best, yes, but picking up which lines can be unwrapped is ... tricky. I'd have to check the exact order, but I think the issue with paths is that there is not a nice clear end marker.

**Comment by stone-zeng** [comment]
Recently I came across another normalization problem, which seems to be related with long path as well (from [ci for zhlipsum](https://github.com/stone-zeng/zhlipsum/runs/458485707)):

```
(/usr/local/texlive/2019/texmf-dist/tex/latex/cjk/texinput/Bg5/c00bsmi.fdx
File: c00bsmi.fdx 2015/04/18 4.8.4
)
[1

] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14]
```

and

```
(/tmp/texlive/2019/texmf-dist/tex/latex/cjk/texinput/Bg5/c00bsmi.fdx
File: c00bsmi.fdx 2015/04/18 4.8.4
) [1

] [2] [3] [4] [5] [6] [7] [8] [9] [10] [11] [12] [13] [14]
```

Is there any hot-fix?

**Comment by josephwright** [comment]
@stone-zeng I'll take a look.

Also, interested in your GitHub Actions set up: does it work as fast as Travis-CI? Do you cache the TeX installation?

**Comment by stone-zeng** [comment]
@josephwright The github action "trigger time" (from commit to the start of ci running) is much less than travis, but other things don't have too many remarkable differences.

I haven't used the cache (but it can be done), since an minimal installation only requires 1–2 min.

**Comment by josephwright** [comment]
I think the best we can do here is `maxprintline = 9999`. Should we make the breaking change and force this on all users?

**Comment by FrankMittelbach** [comment]
it is probably a rather horrifying change in the sense the a lot of people will first spend a lot of time trying to figure out why they have breaking tests instead of suspecting a simple l3build change

What about this strategy:
 - set maxprintline to -1
 - after build.lua has been read check the value
     -  if not -1 all good
     - if still set to 9999 and output a warning at the very end that failures might be due the change
       and the user should explicitly set it back 78 or regenerate their tests

**Comment by josephwright** [comment]
I think we addressed this by moving to a default of `maxprintline = 9999`
