### ISSUE TITLE
Commands undocumented in CLI and doc

### ISSUE THREAD

**Issue by pablgonz** [latex3/l3build#110]
Hey, everybody, I noticed that some commands are not documented anywhere. Specifically `--help` and `--version`. When running `l3build --help` are not listed and the first line of the output (with updated TeXLive is):

```
usage: /usr/local/texlive/2019/bin/x86_64-linux/l3build <command> [<options>] [<names>]
```

I think the right way out should be:

```
usage: l3build <command> [<options>] [<names>]
```

When you run `l3build --version` the output is:

```

l3build: A testing and building system for LaTeX

Release 2020-02-03
```

I think it's prettier this (for me):

```
Copyright (C) 2017-2020 The LaTeX3 Project
l3build: A testing and building system for LaTeX
Release 2020-02-03
```
And one last thing, I miss the `--licence` command, I know it's not mandatory in a _script_, but it's good to have it declared :).

Thanks for everything.

**Comment by josephwright** [comment]
I've fixed the `help` text. I've never come acros `--license`: can you give an example? We don't have a `--help` switch (unknown stuff yields `help`, but `--help` would imply per-target help as in Git, I think). On `--version`, again, based on Git we are doing much the same ...

**Comment by pablgonz** [comment]
@josephwright Thanks for responding, in my mind I was thinking something like this:

```
$ l3build --help

l3build: A testing and building system for LaTeX

usage: l3build <command> [<options>] [<names>]

Valid commands are:
   check        Run all automated tests
   clean        Clean out directory tree
   ctan         Create CTAN-ready archive
   doc          Typesets all documentation files
   install      Installs files into the local texmf tree
   manifest     Creates a manifest file
   save         Saves test validation log
   tag          Updates release tags in files
   uninstall    Uninstalls files from the local texmf tree
   unpack       Unpacks the source files into the build tree
   upload       Send archive to CTAN for public release

Valid options are:
   --config|-c            Sets the config(s) used for running tests
   --date                 Sets the date to insert into sources
   --debug                Runs target in debug mode (not supported by all targets)
   --dirty                Skip cleaning up the test area
   --dry-run              Dry run for install
   --email                Email address of CTAN uploader
   --engine|-e            Sets the engine(s) to use for running test
   --epoch                Sets the epoch for tests and typesetting
   --file|-F              Take the upload announcement from the given file
   --first                Name of first test to run
   --force|-f             Force tests to run if engine is not set up
   --full                 Install all files
   --halt-on-error|-H     Stops running tests after the first failure
   --last                 Name of last test to run
   --message|-m           Text for upload announcement message
   --quiet|-q             Suppresses TeX output when unpacking
   --rerun                Skip setup: simply rerun tests
   --show-log-on-error    If 'halt-on-error' stops, show the full log of the failure
   --shuffle              Shuffle order of tests
   --texmfhome            Location of user texmf tree
   --help                 Print this message and exit
   --version              Print version information and exit
   --license              Print licensing information and exit

Full manual available via 'texdoc l3build'.

Repository  : https://github.com/latex3/l3build
Bug tracker : https://github.com/latex3/l3build/issues
Copyright (C) 2018,2020 The LaTeX3 Project
```

With regard to `--version` ( or `--release` ) I was thinking about this:

```
$ l3build --version

l3build: A testing and building system for LaTeX
Release 2020-02-03
Copyright (C) 2018,2020 The LaTeX3 Project
```

The thing about `--license' is because I had a question about the GPL and LPPL, I don't know if the latter falls into the category for a _script_, anyway, I was thinking about something like that:

```
$ l3build --license

Copyright (C) 2018,2020 The LaTeX3 Project

This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 3 of the License, or
(at your option) any later version.

This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.

You should have received a copy of the GNU General Public License
along with this program.  If not, see <http://www.gnu.org/licenses/>.
```

A related question (just a conceptual one). The `usage` line of `l3build` shows this:

```
usage: l3build <command> [<options>] [<names>]
```
The word `<command>` makes noise to me, I don't know what the correct name is, but (I'm almost sure) it's not `<command>`, I would be more comfortable with `<target>` which is more in line with the code itself (`if options["target"] ==`)...anyway if I'm just playing around...please don't burn me :)

**Comment by josephwright** [comment]
I've made most the the changes, but I'm still not sure about the license business: that's only important for people using the code, rather than the script at the command line, and as for (almost) all team code it's LPPL.

**Comment by pablgonz** [comment]
> I've made most the the changes, but I'm still not sure about the license business: that's only important for people using the code, rather than the script at the command line, and as for (almost) all team code it's LPPL.

@josephwright  Thanks for accepting the suggestion, regarding the license, I think it's an "old perl habit" that I have stuck (it doesn't hurt anyway).

All that remains is to update the documentation with the changes and everything will be OK.

Just a final note to @FrankMittelbach (https://github.com/latex3/l3build/issues/99#issuecomment-534488969)... the world of `l3build` users is small...but it expands day by day :-).
