### ISSUE TITLE
--rerun has no effect in doc target

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/l3build#112]
when I run
```
  l3build doc --rerun usrguide
```
it has no effect and build format and subdirectories nevertheless. This might be just an issue with the 2e build.lua, probably is (not checked), but it would be nice if it works generally as the format build takes a  long time on my machine.

**Comment by josephwright** [comment]
The `--rerun` switch currently only dos anything for the `check` target: it was a shortcut added ages ago. I guess I need to add some additional tests to see if it's active.

**Comment by FrankMittelbach** [comment]
nothing urgent about it but on my machine it would be really useful in the 2e sources as building the format for checking the doc of any file rather takes a long time on my Mac
