### ISSUE TITLE
Feature request: support latexmk

### ISSUE THREAD

**Issue by stone-zeng** [latex3/l3build#113]
At present, the document says (section 4.3)

> However, there is no attempt to create an entire PDF creation system in the style of `latexmk` or similar.

Please consider to support `latexmk` or similar tools, because they are much faster and 'smarter' than the current build process, especially when compiling large docs.

**Comment by pablgonz** [comment]
@stone-zeng It can be done: ) check  (https://github.com/pablgonz/demopkg-jw#heading--4-3)

**Comment by stone-zeng** [comment]
Thank you @pablgonz! Hopefully the latex3 team can adopt your examples in the document.

**Comment by josephwright** [comment]
The point here was really that `l3build` itself does not try any 'cleverness': we don't look at changed files, timestamps or whatever. Contrast not only to `latexmk` but also to `make`. The idea was to be _sure_ we always regenerate files and the for the typesetting runs there is a known 'recipe'.

_Using_ `latexmk` as a tool for some steps is fine, but I'm not sure I'd want to encourage it; rather goes against the point of having a clear build path.

**Comment by pablgonz** [comment]
I think a rookie mistake on my part was trying to use `typesetexe = "latexmk"` on my first attempts with `l3build`, of course I absolutely failed and had to go look at the sources for `l3build` to understand what was going on. 

Perhaps leave a note in the documentation for users of _compiling tools_ about their use along with `specialtypesetting` and `function typeset(file)`.

**Comment by pablgonz** [comment]
@stone-zeng I think this is already covered in the documentation (maybe an example is missing), could it be closed?
