### ISSUE TITLE
unpackdir is incorrect

### ISSUE THREAD

**Issue by stone-zeng** [latex3/l3build#114]
In the document, the default value for `unpackdir` is `builddir .. "/unpack"`, but in the code, there is an extra `-ed` (`builddir .. "/unpacked"`):

https://github.com/latex3/l3build/blob/012e40f5eafbff9a6e0df17f1f892105fbd28e91/l3build-variables.lua#L58

I'm not quite sure whether it's ok to change the default value, as many code may have used it explicitly.

**Comment by josephwright** [comment]
That's purely a doc issue: no-one should be using a hard-coded value for this.
