### ISSUE TITLE
ctan target may fail when path to l3build has spaces

### ISSUE THREAD

**Issue by kdv2005** [latex3/l3build#120]
This is a continuation of #76 and #91: ctan target may fail when path to l3build has spaces

I am using TeX Live (release 2020) on Windows, installed into C:\Program Files\texlive.  Both l3build check and l3build doc complete without errors, but l3build ctan fails.   Here is the log for the [minimal failing example](https://github.com/latex3/l3build/files/4674313/ctan.fail.issue.zip):

```
$ type tex
tex is /c/Program Files/texlive/2020/bin/win32/tex
  
$ type l3build
l3build is /c/Program Files/texlive/2020/bin/win32/l3build
 
$ kpsewhich l3build.lua
c:/Program Files/texlive/2020/texmf-dist/scripts/l3build/l3build.lua
  
$ l3build --version
 
l3build: A testing and building system for LaTeX
 
Release 2020-03-25
Copyright (C) 2014-2020 The LaTeX3 Project
 
$ l3build check
 
$ l3build ctan
Running l3build with target "check" for module .
Script file c:/Program not found
 
====================
Tests failed, zip stage skipped!
====================
```

**Comment by josephwright** [comment]
I know it's a 'reverse dupe', but I'm collecting up issues on this in https://github.com/latex3/l3build/issues/120
