### ISSUE TITLE
Wrong path to .diff when running on the root of the repository

### ISSUE THREAD

**Issue by PhelypeOleinik** [latex3/l3build#123]
For instance, if I make a local change to [`d3dvipdfmx.tlg`](https://github.com/latex3/latex3/blob/master/l3kernel/testfiles/d3dvipdfmx.tlg) to force an error, then run `l3build check` (or `l3build check d3dvipdfmx` to make it shorter) with the terminal open in the `latex3` folder, the end of the `l3build` run reports:
```none
  m3token004 (163/164)
  m3token005 (164/164)

  Check failed with difference files
  - ../build/test/d3dvipdfmx.luatex.diff
  - ../build/test/d3dvipdfmx.pdftex.diff
  - ../build/test/d3dvipdfmx.uptex.diff
  - ../build/test/d3dvipdfmx.ptex.diff

phelype@phelype ~/d/latex3>
```
indicating that the `build` folder is a directory above (`../build`), which is wrong, rather than in the current directory (`./build`).

This is not too serious, but it's mildly annoying to remove a dot when copy-pasting that to open the `.diff`.

**Comment by josephwright** [comment]
Not really a bug: `l3build` works recursively with independent processes, and the 'terminal' process is responsible for printing this information.

**Comment by PhelypeOleinik** [comment]
Ah, okay, I didn't know that.  Thanks!

**Comment by blefloch** [comment]
Could l3build have an additional --relative-path option, which the top-level
l3build would construct for the lower-level ones, and which would help give the
correct path to diffs?

**Comment by FrankMittelbach** [comment]
would you really control that via an option? I think it is clearly a config thing (so perhaps some variable there but something set on the command line), or would it?

**Comment by blefloch** [comment]
On 7/23/20 1:58 AM, Frank Mittelbach wrote:
> would you really control that via an option? I think it is clearly a config
> thing (so perhaps some variable there but something set on the command line), or
> would it?

I have no opinion on that, just that it seems feasible so maybe a bit too
quickly closed.
