### ISSUE TITLE
target install fails in miktex

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#125]
Running `l3build install` in (for example) `latex2e/base`  fails with 

~~~~
Creating/installing dev-version in latex-dev
"\\?\C:\Users\Nililand2020\Documents\OtherGit\latex3\latex2e\base"
CMD.EXE wurde mit dem oben angegebenen Pfad als aktuellem Verzeichnis gestartet.
UNC-Pfade werden nicht unterstützt.
Stattdessen wird das Windows-Verzeichnis als aktuelles Verzeichnis gesetzt.
"\\?\C:\Users\Nililand2020\Documents\OtherGit\latex3\latex2e\base"
CMD.EXE wurde mit dem oben angegebenen Pfad als aktuellem Verzeichnis gestartet.
UNC-Pfade werden nicht unterstützt.
Stattdessen wird das Windows-Verzeichnis als aktuelles Verzeichnis gesetzt.
[... many more of the same ...]
Datei lppl.tex nicht gefunden
~~~~

In another case the last line was 

~~~~
Das Verzeichnis oder die Datei kann nicht erstellt werden.
~~~~

Installation with texlive worked fine in both cases.

**Comment by josephwright** [comment]
I''m not sure we can do much here: as TeX Live works, it's not a PATH issue. Do we have more idea of what's up?

**Comment by u-fischer** [comment]
Difficult as the failures are so varied (and seem to have changed since I opened this issue). I just tried in hologo: 

* `l3build check` worked (with test failures, but only because some pathes are too long in miktex and couldn't be normalized)
* `l3build ctan` failed with 
   ~~~~
   Running l3build with target "check" for module .
   Script file C:/Users/Nililand2020/AppData/Local/Programs/MiKTeX not found
  ~~~~
* l3build install failed with 
~~~~
Der Befehl "C:\Users\Nililand2020\Documents\TeXroots\UFlocaltexmf" ist entweder falsch geschrieben oder
konnte nicht gefunden werden.
...ms/MiKTeX 2.9/scripts/l3build/l3build-file-functions.lua:182: Unable to change working directory to '{C:/Users/Nililand2020/Documents ... list of all my local roots ... }`
~~~~
To make it even more confusing the `UFlocaltexmf`  mentioned first is the *second* root in the list.

It could be that all failures are related to the space in the miktex path (I should have removed them when I installed miktex but forget at that time).

**Comment by josephwright** [comment]
I think we try to fix the issues about spaces and then see what happens - it's going to be tough otherwise to track this down.

**Comment by u-fischer** [comment]
I tried on my laptop where I have a miktex without spaces in the path. `l3build ctan` then starts (it fails because of the test failures).

`l3build install` still fails, and the problem here is, that `kpsewhich --var-value=TEXMFHOME` in miktex doesn't report the value of the environment variable (which contains only one path) but the full list of texmf roots I have.

If I use `l3build install --texmfhome=C:\Users\Nililand-Surface\Documents\gitinstalltexmf`  I get past the error, but at the end I get messages about invalid directories and nothing is copied. And if I try again I get messages like this

~~~~
Ein Unterverzeichnis oder eine Datei mit dem Namen "\\?\C:\Users\Nililand-Surface\Documents\gitinstalltexmf\tex\generic\hologo" existiert bereits.
~~~~

Perhaps we should simply document "l3build requires texlive" ;-(

**Comment by FrankMittelbach** [comment]
> `l3build install` still fails, and the problem here is, that `kpsewhich --var-value=TEXMFHOME` in miktex doesn't report the value of the environment variable (which contains only one path) but the full list of texmf roots I have.

that sounds like a bug in the kpsewhich implementation, or not?

> 
> Perhaps we should simply document "l3build requires texlive" ;-(

not really that great. but is it only the install target that fails or also others? 

by the way what happens if the directories below TEXMFHOME do exist already? does it work then?

**Comment by davidcarlisle** [comment]
even in texlive TEXMFHOME can be a list, it just usually isn't

the texlive `texmf.cnf`  says

```
% Per-user texmf tree(s) -- organized per the TDS, as usual.  To define
% more than one per-user tree, set this to a list of directories in
% braces, as described above.  (This used to be HOMETEXMF.)  ~ expands
% to %USERPROFILE% on Windows, $HOME otherwise.
TEXMFHOME = ~/texmf
```

which means 

```
local function gethome()
  set_program("latex")
  local result = options["texmfhome"] or var_value("TEXMFHOME")
  mkdir(result)
  return abspath(result)
end
```

should probably split on `:` (or `;` on windows) and take the first

**Comment by josephwright** [comment]
The issue with paths comes about from `lfs.chdir()`. You can see the effect with 
```lua
print(lfs.currentdir())
lfs.chdir(".")
print(lfs.currentdir())
```
which gives the weird UNC prefix ``\\?\`` with MiKTeX but not with TeX Live. I think that's a MiKTeX bug.

**Comment by josephwright** [comment]
On path(s), I have to say I thought `TEXMFHOME` had to be  a unique value, the same as `%HOME%` (Windows)/`~` (Unix) - seems logical to me ....

**Comment by u-fischer** [comment]
> that sounds like a bug in the kpsewhich implementation, or not?

Not sure. As David commented texmfhome can contain a list.  The question is if it should retrieve the environment variable. 

But further tests gave:
    
       kpsewhich --var-value=TEXMFHOME`    : full list of texmf 

but 

       kpsewhich --var-value=texmfhome
       C:\Users\Nililand-Surface\Documents\gitinstalltexmf

First time that windows is case sensitive ;-(

I will open an issue at miktex to ask if that is intended.

@josephwright  I will also open an issue about the `\\?\`

**Comment by davidcarlisle** [comment]
`\\?` isn't necessarily wrong though, if what follows is of the right form

 https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path

> "For file I/O, the `'\\?\'` prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system." Parsing includes translating forward slashes to backslashes, or interpreting the . and .. pseudo directories.

so I think if normalising the file paths we can strip leading `\\?`

**Comment by josephwright** [comment]
> `\\?` isn't necessarily wrong though, if what follows is of the right form
> 
> https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path
> 
> > "For file I/O, the `'\\?\'` prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system." Parsing includes translating forward slashes to backslashes, or interpreting the . and .. pseudo directories.
> 
> so I think if normalising the file paths we can strip leading `\\?`

Probably for the best: we can do that in the current `abspath()` function.

**Comment by zauguin** [comment]
> so I think if normalising the file paths we can strip leading `\\?`

That might cause trouble when long paths are involved. Paths starting longer than 260 characters only work when prefixed with `\\?`. (Of course that might be something we just have to accept if cmd.exe doesn't support such paths anyway)

**Comment by josephwright** [comment]
> `\\?` isn't necessarily wrong though, if what follows is of the right form
> 
> https://stackoverflow.com/questions/21194530/what-does-mean-when-prepended-to-a-file-path
> 
> > "For file I/O, the `'\\?\'` prefix to a path string tells the Windows APIs to disable all string parsing and to send the string that follows it straight to the file system." Parsing includes translating forward slashes to backslashes, or interpreting the . and .. pseudo directories.

May be true but we are getting errors when the result is passed back to OS, so something's not quite right!

**Comment by josephwright** [comment]
> > so I think if normalising the file paths we can strip leading `\\?`
> 
> That might cause trouble when long paths are involved. Paths starting longer than 260 characters only work when prefixed with `\\?`. (Of course that might be something we just have to accept if cmd.exe doesn't support such paths anyway)

The limit remains there: a path of over 260 chars is not allowed.

**Comment by josephwright** [comment]
I've done a few quick tests: some things work with ``\\?\`` at the Command Prompt, some don't - I think as we need some 'basic' functionality from `cmd.exe`, we can't use them.

**Comment by zauguin** [comment]
> The limit remains there: a path of over 260 chars is not allowed.

I don't understand what you are saying. Do you mean that we don't want to support longer paths?

**Comment by josephwright** [comment]
@zauguin I'm saying that the Command Prompt, as opposed to the Windows low-level file API, simply can't work with such paths. Try for example `cd \\?\<whatever>`. We need various `os.excute()` bits and pieces, which ultimately need the Command Prompt, so that defines what is 'allowed'. Anyone using Windows with files that Command Prompt can't access deserves all the trouble they've brought on themselves, in my opinion :)

**Comment by u-fischer** [comment]
I think that mean that returning `//?/` is not an error from miktex, and l3build should handle it?

**Comment by josephwright** [comment]
@zauguin I had a bit more of a think and did some more test :) I wondered if the issue is that we normalise ``\`` to `/`, and that will break with ``\\?\``. However, simply adjusting that doesn't work. If I try something like
```
if not exist test mkdir test
```
or
```
if not exist C:\temp\test mkdir C:\temp\test
```
at the Command Prompt then all is fine. However, if you use
```
if not exist \\?\C:\temp\test mkdir \\?\C:\temp\test
```
then the test doesn't work and `mkdir` complains.

That's one example of how a lot of the system-dependent file system operations are done in ```l3build```. It might be possible to rework them all to use bits of `lfs` and/or Windows utilities that don't choke on UNC paths, but that seems quite a lot of work for edge case problems (long paths that probably I'd avoid anyway on Windows).

If there are no objections, I think the best fix is to remove the ``\\?\`` prefix from paths if it's present: that will get the common cases working.

**Comment by u-fischer** [comment]
I think it is quite ok to document restrictions (length, charset) regarding the pathes. Only the scripts should if possible work if they are stored in a path with non-ascii user names and spaces, as people will have installation pathes like

       `C:\Users\andré\Appdata\MiKTeX 2.9\ ...`

and forcing them to reinstall miktex would be a bit much, but other files are easily relocated to sane locations.

**Comment by FrankMittelbach** [comment]
given that TEXMFHOME is allowed to list several directories (which I would hope are then properly searched one after another) it should be enough in my opinion to list the restrictions and tell people that, if their installation doesn't meet those they need to setup a second texmf tree, sayy
```
  C:\Users\andré\l3build\texmf
```
and tell l3build in the build.lua (or on the command line) to use that tree for installation and have their TEXMFHOME variable altered to include that as the first or second tree.

**Comment by u-fischer** [comment]
> and tell l3build in the build.lua (or on the command line) to use that tree for installation and have their TEXMFHOME variable altered to include that as the first or second tree.

In view that the handling of the texmfhome variable is a bit curious in miktex and that the meaning/use of texmfhome can be a bit overloaded when you have a number of tex systems, could l3build perhaps at first check for a special environment variable, e.g. L3BUILD_INSTALL_TEXMF?

**Comment by josephwright** [comment]
> > and tell l3build in the build.lua (or on the command line) to use that tree for installation and have their TEXMFHOME variable altered to include that as the first or second tree.
> 
> In view that the handling of the texmfhome variable is a bit curious in miktex and that the meaning/use of texmfhome can be a bit overloaded when you have a number of tex systems, could l3build perhaps at first check for a special environment variable, e.g. L3BUILD_INSTALL_TEXMF?

Quite doable: do we have a particular  view on the name?
