### ISSUE TITLE
Missing normalization for `luatexbase.new_luafunction` ids

### ISSUE THREAD

**Issue by zauguin** [latex3/l3build#127]
See the test failure at https://travis-ci.org/github/latex3/latex3/jobs/726414871:

> ```
> *** ../../build/test/m3benchmark000.luatex.tlg	2020-09-11 20:52:28.021389999 +0000
> --- ../../build/test/m3benchmark000.luatex.log	2020-09-11 20:52:28.313243999 +0000
> ***************
> *** 2,9 ****
>   Don't change this file in any respect.
>   (l3benchmark.sty
>   Package: l3benchmark ....-..-.. L3 Experimental benchmarking
> ! Lua function __sys_elapsedtime: = 9
> ! Lua function __sys_resettimer: = 10
>   \g__benchmark_nesting_int=\count...
>   \g__benchmark_duration_int=\count...
>   \g__benchmark_time_int=\count...
> --- 2,9 ----
>   Don't change this file in any respect.
>   (l3benchmark.sty
>   Package: l3benchmark ....-..-.. L3 Experimental benchmarking
> ! Lua function __sys_elapsedtime: = 10
> ! Lua function __sys_resettimer: = 11
>   \g__benchmark_nesting_int=\count...
>   \g__benchmark_duration_int=\count...
>   \g__benchmark_time_int=\count...
> ```
> 

I think it would be good to normalize these.

**Comment by josephwright** [comment]
I'll take a look

**Comment by josephwright** [comment]
Could you see if this works?

**Comment by zauguin** [comment]
> Could you see if this works?

Sadly no. It only applies the normalization if there is no LuaTeX specific tlg file and the default engine is not LuaTeX, but then there shouldn't be any `Lua function`s to begin with.

**Comment by josephwright** [comment]
Try now :)

**Comment by zauguin** [comment]
> Try now :)

Sorry for the delay, I had missed that comment. It works fine now :)
