### ISSUE TITLE
Use system zip capablities on Windows

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#13]
Recent Windows allow something like
```
 powershell Compress-Archive -Path <path> -DestinationPath <zip-file>
```
Probably we should use this rather than relying on a third-part `zip`.

**Comment by josephwright** [comment]
Reference material at https://msdn.microsoft.com/en-us/powershell/reference/5.1/microsoft.powershell.archive/compress-archive makes no mention of dealing with line endings. Probably with PowerShell (or from Lua) we could normalise these, but that seems like quite a step. For the present, perhaps easiest to stick with the approach of using a third-party tool (unless someone else wants to pick this up).

**Comment by josephwright** [comment]
For the interested, what we currently do is zip up all of the non-binary files with line end normalisation (`-ll`), then add the binary ones without that. So to use the Windows zip tool we'd have to first normalise line ends in a copy of the source files, then make the zip in one go. That's of course doable by quickly reading/rewriting every file in the area used to build the release, but it seems quite painful.

**Comment by pablgonz** [comment]
@josephwright Is this still valid?

**Comment by josephwright** [comment]
Ah, we can close: it got covered by bring zipping 'in house'
