### ISSUE TITLE
Enable tree copying throughout internals

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#14]
At present, tree copying support is partial (see https://github.com/latex3/l3build/commit/9e1b6be4f3b8f7c15dbb762374fe03b98ffaa816, _etc._). This should likely be extended to be consistent across the code. Possibly one or more flags may be needed to denote whether trees should be 'flattened'.

**Comment by josephwright** [comment]
@dffischer Thoughts on this would be welcome.

**Comment by josephwright** [comment]
@dffischer I've been reading over `tree()` for this and there are a couple of things I'd like your input on. First, is there a particular reason for returning both the key and value in the way  you've set up: from the use cases, it looks like the key should be the value, and the former should just be arbitrary. Secondly, is there any reason to retain `filelist()`?

**Comment by dffischer** [comment]
Keeping `filelist()` around is necessary in a way as `tree()` uses it. Apart from that, all occurrences of the former could be replaced with the latter, but I recommend doing so step-by-step or even only when the need arises, as this often entails the modification of further code to correctly deal with files scattered among subdirectories. Pull request #29 is an example of such an aftermath.

I understand that flattened trees are often easier to handle, but would vote against this practice in general. Firstly, files with the same name from different directories could obviously clash. Apart from that, flattening distorts references to a file, as I exemplified in [a comment to the original pull request containing `tree()`](https://github.com/latex3/latex3/pull/360#discussion_r116803208).

**Comment by josephwright** [comment]
@dffischer I see the point about trees but as we work on the basis of names being unique in the TeX tree that should really not normally be an issue. (Names being the same should almost always be deliberate, for example for engine-specific over-rides of specific files, and even there it can get people into trouble!)

**Comment by josephwright** [comment]
@dffischer Also worth remembering that the 'proper' way to deal with trees is to set `TEXINPUTS` (as @davidcarlisle will otherwise point out ;))

**Comment by josephwright** [comment]
I entirely see the point about doing it a bit at a time: this is as much a marker that there is a process as anything else. (As I've noted elsewhere, I'm trying to be reasonably systematic in this new repo in logging issues for anything major.)

**Comment by dffischer** [comment]
`TEXINPUTS` is also the only proper way I know to consider files from multiple directories at once. It is already used in the `tex()` function with `runtool()`. As this strategy may in the future become handy again to combine `typesetdir` or `testdir` with `unpackdir` and `localdir` on the fly, I leave this here as a reminder.

**Comment by josephwright** [comment]
I'm going to close here: I think the 'do it a bit at a time' case is well made.

**Comment by josephwright** [comment]
Just to note that although this is being done piecewise, it probably is largely covered in addressing #2 fully.
