### ISSUE TITLE
l3build development is not compatible with l3build use

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#143]
In general, we have a global texmf domain, a local texmf domain and the current directory domain.
When using a package for example, all 3 domains may be used.
There is no assumption on the location where things must be installed, except for `l3build`.

Running `l3build ...` will select the global domain for any `l3build*.lua` file.

When running `texlua l3build.lua ...` things get complicated.
For example, where can `l3build-clean.lua` come from:

- if there is only a global `l3build` it can only come from the global domain,
- if there is a `l3build-clean.lua` installed locally it will be chosen,
- if there is a `./l3build-clean.lua` in the current working directory then
  * if there is also a `l3build.lua` then the current working version will be chosen
  * else either the local or global version will be chosen.

If you run `texlua l3build.lua clean` then the current working `./l3build-clean.lua` will be required, then for each module an installed `l3build-clean.lua` will be required not the working one, this is because tasks are no longer run from the same directory. In fact, the current working version will also be required for the sub targets, only if it is also installed either locally or globally.

The workflow within `l3build` directory is
```
l3build install
texlua l3build.lua clean...
```
But then it overwrites any previously installed `l3build` customized for everyday use.
This is where l3build development is not compatible with l3build use.

I see at least two starting points to solve this issue,
1) use `lfs.chdir` instead of `cd` in the definition of `run` (push/popd like)
2) add a `--main` CLI option to set `maindir` from the command line. At the same level than `--help` and `--version`.

Using `maindir=..` in a local `build.lua` would require `build.lua` to be loaded earlier (it makes me think of `% !TeX root=...`)

Point 2) is somehow related to issue [#63 running l3build in the testfiles folder](https://github.com/latex3/l3build/issues/63)

I have not yet completely understood the pros and cons of the sub target mechanism related to the `run` function. My actual feeling is that point 1) is a must do (and also point 2)

In a recent discussion, it came out that the required tool to develop `l3build` was TL+git. Here we can see that `l3build` is required to develop `l3build`, amazing.

**Comment by josephwright** [comment]
I think it's important to remember that very few people use non-standard copies of `l3build`: probably fewer than 6 people. The thing to remember is that there is a check for path. So within the `l3build` directory, one can force using the local copy with
```
texlua ./l3build.lua
```
whilst if one wishes to use a modified version for checking say LaTeX2e then
```
kpsewhich l3build.lua 
texlua <full-path-to>/l3build.lua
```
will do the job. On a *nix system that can be shortened to
```
texlua $(kpsewhich l3build.lua)
```
though of course that doesn't work on Windows.

**Comment by josephwright** [comment]
> ```
> l3build install
> texlua l3build.lua clean...
> ```
> 
> But then it overwrites any previously installed `l3build` customized for everyday use.
> This is where l3build development is not compatible with l3build use.

That's not dissimilar to the case for macro programming: one possible solution is to have multiple 'local' trees and for example the `auxtrees` idea. (@u-fischer is the master of this.) For myself, I tend toward simply installing/uninstalling as required: at any point, `l3build` should be 'ready to run' with the possible exception of normalisation changes (usually seen between TL versions).

**Comment by jlaurens** [comment]
The `texlua ./l3build.lua` won't work, you must provide the full path. Giving a relative path is not compatible with `cd`.

That's not very comfortable... and counter intuitive.

Also, adding another local tree and switching between local trees seem weird to me.

So I'll stick to install/uninstall when I happen to make it work properly, but it is still an issue...

**Comment by josephwright** [comment]
> The `texlua ./l3build.lua` won't work, you must provide the full path. Giving a relative path is not compatible with `cd`.

Always works for me in the `l3build` dir.

> That's not very comfortable... and counter intuitive.
> 
> Also, adding another local tree and switching between local trees seem weird to me.
> 
> So I'll stick to install/uninstall when I happen to make it work properly, but it is still an issue...

Again, tends to work for me :)

**Comment by u-fischer** [comment]
auxtrees aren't really relevant here. l3build is an application and the tex systems don't look for the script through all texmf trees (which is imho quite sensible). In the few cases where I actually wanted to test something with the development version, I did a copy&paste. But if I needed more I would think in terms of an application: I would create a l3build-dev.exe which suitable search path, or create a second texsystem and switch the PATH variable.

**Comment by josephwright** [comment]
@u-fischer  Thanks: I'd forgotten that scripts work differently WRT trees.
