### ISSUE TITLE
Add support for TEST environments

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#15]
Taken from https://github.com/latex3/latex3/issues/375, there are cases where using `\TEST{...}{...}` isn't optimal. Some support is needed for an environment-based approach.

**Comment by josephwright** [comment]
@ benzea Does branch https://github.com/latex3/l3build/tree/testenv do what you want in terms of an environment form?

**Comment by blefloch** [comment]
`\STARTTEST...\ENDTEST` seems like an odd pairing: ConTeXt has start...stop and LaTeX has begin...end. I'd say pick one.

**Comment by josephwright** [comment]
@blefloch  Was based on the fact that we already have `\START` ... `\END`.

**Comment by benzea** [comment]
@josephwright Yes, I am happy with that. In particular if the documentation has a note on how to flush the page out (I am happy to propose changes to latex3/articles/lua-test-suite.tex).

**Comment by blefloch** [comment]
@josephwright  Ah, I forgot about that.  Then what you had is fine (what you have now too).

**Comment by josephwright** [comment]
I guess I'll see what @FrankMittelbach feels about the naming.

**Comment by davidcarlisle** [comment]
On 30 June 2017 at 04:12, Bruno Le Floch <notifications@github.com> wrote:

> \STARTTEST...\ENDTEST seems like an odd pairing: ConTeXt has start...stop
> and LaTeX has begin...end. I'd say pick one.
>
>
test2e.tex has \START \END and looks like regressiontest copied the same
so using that here is Ok I think although I agree begin-end start-stop are
perhaps more natural pairings in general.

**Comment by FrankMittelbach** [comment]
> I guess I'll see what @FrankMittelbach 
> <https://github.com/frankmittelbach> feels about the naming.

I don't mind either way

I guess \END was a bit weird back then given that we used \START and 
given that it is more like \stop in terms of it not executing the full 
\end{document}. But changing that seems overkill so

**Comment by josephwright** [comment]
OK, we'll stick with `\BEGINTEST` then: probably more natural. I'll look to do the documentation part too and merge into master.
