### ISSUE TITLE
mark custom targets in help

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#152]
Section 5.6 of the dtx suggests how to add new targets.
Custom targets should be marked (for example with a "(*)" in `l3build --help` output)

**Comment by josephwright** [comment]
I guess the issue then is what counts: depending on the use case, standard targets can be removed, so there is not a strictly fixed list.

**Comment by FrankMittelbach** [comment]
Is it in any way relevant for the user to know that something is a custom target? I can't see why that it is helpful in a practical way.

**Comment by jlaurens** [comment]
If you have a problem with a builtin target, you ask the l3build team
If you have a problem with your custom target, then it is yours and you should ask yourself.

So far there is not a desperate need for a custom marker.

But when the user is not the one who wrote the initial `build.lua`, or when he forgot what is inside the `build.lua` because it was written a long time ago, or when the `build.lua` was just adapted from existing material, then knowing that a target is a custom one really helps.
