### ISSUE TITLE
file-functions: `cp` weirdness

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#161]
The [definition of cp](https://github.com/latex3/l3build/blob/4e5fec7a09fb9fede5a0589d90a1dbcd1276c52c/l3build-file-functions.lua#L215) starts reading
```
-- Copy files 'quietly'
function cp(glob, source, dest)
  local errorlevel
  for i,_ in pairs(tree(source, glob)) do
```
The first argument is a `glob` like "\*.\*" to pick only names with extensions.

A usage example is at line [77 of `l3build-check.lua`](https://github.com/latex3/l3build/blob/4e5fec7a09fb9fede5a0589d90a1dbcd1276c52c/l3build-check.lua#L77), which reads
```
for _,i in ipairs(filelist(testsuppdir)) do
  cp(i, testsuppdir, testdir)
end
```
The propose is to get the list of all the items in `testsuppdir` and copy them to `tesdir`.
The item name `i` is considered as a glob, which may be problematic because of "+", "*" and "?" may unexpectedly be active characters in the name.

There should be a `copy(name, source, dest)` which first argument is not a glob and should be used instead.

**Comment by josephwright** [comment]
Er, no one should have files with `*` or `?` in the name: I'm not sure it's even possible! (`cmd.exe` would I suspect just give up.)

**Comment by jlaurens** [comment]
on unix
```
touch "a?b*c.text"
```
is legal...

**Comment by davidcarlisle** [comment]
It is a legal filename on unix but I think the model in l3build  is that a string in lua tables such as 

`textfiles          = textfiles          or {"*.md", "*.txt"}`

The `*` is a glob so if you literally want a file called `*.md` then you need to quote it or (better just say it is not supported)

So I think by the time you get to the cp function all strings should have been quoted by the author of the build.lua file or be a glob so I don't think you need another function here.


There are other implied restrictions for example on unix you can have a file with a double quote in the name but such a file can not be input to tex at all as its file reading primitives give no possibility to quote/escape  the `"`

**Comment by josephwright** [comment]
> on unix
> 
> ```
> touch "a?b*c.text"
> ```
> 
> is legal...

Sure but not on Windows, and we are looking at a cross-platform tool.

**Comment by FrankMittelbach** [comment]
> The `*` is a glob so if you literally want a file called `*.md` then you need to quote it or (better just say it is not supported)

Since we want standard across platforms, I think the answer is clearly that we don't support such type of unix file names.

**Comment by jlaurens** [comment]
Yes, just like soft links, only a common denominator should be supported.
But things should also be made explicit and the final user should really have an info when an "illegal" name is used.
So these file names must be tested against definite rules and filtered out if necessary, for example in a `copy(item, source, dest)` method.

**Comment by josephwright** [comment]
As with the `"` issue I've just closed, I think here again these are 'cross-platform policy disallowed'.
