### ISSUE TITLE
'**.tex' glob in the dtx

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#166]
The doc for non-standard source layouts reads
"the glob syntax \texttt{**/*.\meta{ext}} may be useful"

In the actual implementation "\*\*/\*.ext" is equivalent to "\*/\*.ext", patterns are respectively `^.*.*%/.*%. ext $` and `^.*%/.*%.ext$`.

I guess that this comment is motivated by standard globing extensions where * does not pass through directory separators whereas ** does.

Adopting a glob flavor closer to the standards would help.

**Comment by josephwright** [comment]
I'm not sure what you mean: we have `**` for recursive globs, and that's what happens. (It's non-standard but useful.)

**Comment by jlaurens** [comment]
Sorry I did not understand the code, sometimes globs are called patterns, that mislead me.
