### ISSUE TITLE
Enhancement: l3build/examples are not easily downloaded

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#171]
It is not straightforward to test the examples referenced in the dtx.
The url points to a GitHub folder but we have no download button.
We must step up and clone or download the whole l3build folder.

If this subfolder is turned into a dedicated project, then one can download the zip from GitHub and make some live tests.

l3build-examples or even l3build-playground for project names seem natural to me.

**Comment by zauguin** [comment]
I don't see this as an issue. Basically I see three typical uses for the examples:

  * A user wants to browser though them to get a general impression how the system works. There is no real need to download them for that, so it doesn't matter if they are part of a bigger download.
  * A user wants to use one of them as a template for their own project. In this case probably only one of them is needed, so even bundling all examples would be too much. But normally you only need the `build.lua` and it is easy to download a single file. This would be an argument in favor of splitting all examples into separate projects, but that would introduce too much overhead for the other use-cases.
  * A `l3build` developer wants to have some variety of files for testing changes/experimenting with new features/... . But developers will normally have the repository checked out anyway, so there is no need to separate it.

Additionally there would be the disadvantage that they would be decoupled from the corresponding l3build version, making it more complicated to add examples demonstrating new features.

**Comment by jlaurens** [comment]
You can't just browse examples to see how things work
Real life demos are more convincing and need less explanation.

The underlying idea is to have l3build initialize some folder based on templates.

**Comment by zauguin** [comment]
> The underlying idea is to have l3build initialize some folder based on templates.

If we at some point want l3build to initialize some folder based on templates (probably based on the current examples if I understand you correctly), than that would mean that we need to distribute these with l3build. So we would not want them to be in a separate repository.
