### ISSUE TITLE
LuaTeX in TL'21 fixes the out-by-one issue

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#178]
Pre-testing for TL'21, it seems LuaTeX's 'out by one' issue with log files is fixed. That's good in a way, but means quite a few `.tlg` files break. We can adjust the `l3build` code, but then we have a difference between TL'20 and TL'21 (onward). Usual policy is 'tough': are we happy to make the switch (and ensure the upload only hits the latest TL release)?

If we do alter, there will still be some `.tlg` changes: the reality is we can't normalise everything.

**Comment by FrankMittelbach** [comment]
I would say bite the bullet and adjust the .tlgs after the release is out. how many are we talking about roughly?

**Comment by josephwright** [comment]
@davidcarlisle  suggests the change is actually no wrapping at all: I'm not clear on that! Could others test?

**Comment by davidcarlisle** [comment]
@josephwright seems I was mistaken: the actual test failure in hyperref shows as a diff against one long line from a message wrapped over two lines, but it seems the out-by one has affected l3build's normalisation of the line breaks but we can check that after the change you proposed here.  I just checked the raw logs of the test with tl2020 and 2021 and they only differ apart from obvious file and version updates in a one character change in linebreaking.
