### ISSUE TITLE
Improve approach to multiple sets of tests

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#18]
Currently we have `--testfiledir|-t` but this requires each set of non-standard tests be run manually. Better would be if several test 'sets' could be run automatically. The new `call()` function should allow this with some modifications: probably something like
```lua
for _,dir in (<set-of-testfile-dirs>) do
  call(".", "check", <some-over-ride-setting-using-dir>)
end
```
where the current `--testfiledir` could be set for each call. The only issue then becomes the naming for the 'set of dirs' (or similar) function.

**Comment by josephwright** [comment]
Probably best to extend `call()` to take a third argument: 'command line parameters', which defaults to 'those given to the parent'.

**Comment by josephwright** [comment]
I suspect we want to stick with the idea that each 'set' of tests is in a separate directory with 'some config' (as for the 2e `TU` tests). Does that seem about right? I've more-or-less worked out how to support that in a single main run, and it doesn't need lots of extra mechanisms for `.tlg` files.

**Comment by davidcarlisle** [comment]
On 3 July 2017 at 21:13, Joseph Wright <notifications@github.com> wrote:

> I suspect we want to stick with the idea that each 'set' of tests is in a
> separate directory with 'some config' (as for the 2e TU tests). Does that
> seem about right? I've more-or-less worked out how to support that in a
> single main run, and it doesn't need lots of extra mechanisms for .tlg
> files.
>
> Yes I think one directory per format (for example) is fine if it's
possible to fire them all off with a single check or ctan build.

**Comment by FrankMittelbach** [comment]
Am 03.07.2017 um 23:11 schrieb David Carlisle:
> 
>  > Yes I think one directory per format (for example) is fine if it's
> possible to fire them all off with a single check or ctan build.

you're sure? For example around 2e we have different areas which I don't 
think would mix too well. If, for example, there are changes made in the 
tools directory it is fairly pointless to run all other tests as well 
(in fact you would even usually want to (at least initially) limit your 
checks to a fraction of the tools tests) so having everything in a 
single directly doesn't seem to gain anything given that right now we do 
have an easy way to fire up all tests before we make a release.

Or differently what do we gain from throwing them all in one dir?

**Comment by wspr** [comment]
Isn’t “everything all in one directory” what we’ve currently got, Frank? I assume Joseph is proposing moving to a model in which you can have multiple directories of tests, with possible differences in configuration between each directory.

A cheap way of achieving similar is simply to have multiple build.lua files with slightly different setups in each.

**Comment by FrankMittelbach** [comment]
then maybe I totally misunderstood what Joseph was trying to say

**Comment by josephwright** [comment]
@FrankMittelbach  The scenario I'm considering is where you have tests which in some way need different underlying setups, for example plain _versus_ LaTeX, ability to search the TeX tree on-and-off, _etc._ This can't (currently) be covered in one `testfiledir` as all of the tests get the same settings.

At present, I've added the switch `--testfiledir` to allow picking an alternative set of tests at the command line. What happens then is `l3build` looks for a `configu.lua` in the given directory and applies it before running the tests. We have this set up for `latex23-public/base`: `testfiles` is the 'vanilla' version, `testfiles-TU` allows `texmf` searching and runs tests purely for XeTeX and LuaTeX.

The limitation with `--testfiledir` is you have to apply it by hand. I think I can arrange that we define a list of test 'setups' (or perhaps 'sets'), each one in a separate directory, such that a top-level `build.lua check` runs all of them. (Aside: a good name for the table here? I was thinking `testfilesets` or `testsetups` or ...)

The question then is do we want this 'one directory per test setup'. The upside is the code is written and is simple, the downside is you have to copy `.lvt` files if you want the _same_ tests but with _different_ setups. Now, I think the latter is quite unlikely, and is better covered in a way similar to the driver tests for L3 (stub loader `.lvt` files and a common 'payload'). Supporting different test setups in one dir is doable I think but needs additional `.tlg` handling, _etc._

Before I implement something, I want to be sure I'm going the right way, not just in terms of ease of coding but also outcomes. (Of course, the need for different test set ups for the same code is probably limited to our own use plus a few people writing generic code which might arguably be tested on plain/LaTeX/ConTeXt.)

**Comment by josephwright** [comment]
@wspr  Of course, I didn't mention the approach 'have a set of different `.lua` files' :) That is the easiest way to do things but again means we can't for example ensure that `build.lua ctan` runs _all_ of the tests. (This is a concern for the 2e kernel, for example.)

**Comment by josephwright** [comment]
What I guess I'm trying to do is make it easy to run these situations: there are ways of doing it, but what I'd like as a 'user' is a simple configuration switch. I _think_ having multiple directories, each of which may have `config.lua` in it to adjust test settings is quite clear. Does that seem right?

**Comment by josephwright** [comment]
BTW, note the parallels with https://github.com/latex3/l3build/issues/21: one could use 'magic' comments to adjust settings rather than a separate `config.lua` file, thought I suspect for any significant set of tests that would become more trouble than it was worth.

**Comment by wspr** [comment]
I agree the config.lua approach seems better for the time being. Can always add magic comments later if we want to support more crazy schemes but I think the lightweight approach is better for now.

**Comment by FrankMittelbach** [comment]
Am 04.07.17 um 09:54 schrieb Joseph Wright:
> The question then is do we want this 'one directory per test setup'. The 
> upside is the code is written and is simple, the downside is you have to 
> copy |.lvt| files if you want the /same/ tests but with /different/ 
> setups. Now, I think the latter is quite unlikely, and is better covered 
> in a way similar to the driver tests for L3 (stub loader |.lvt| files 
> and a common 'payload'). Supporting different test setups in one dir is 
> doable I think but needs additional |.tlg| handling, /etc./

ok I guess I understand now (maybe).

My main wish is that by default things run as automatic as possible 
which means supplying is switch on the command line is inferior to  just 
saying check and get everything tested

A switch is fine if you want to restrict things like only testing one 
engine but getting everything tested should be for free and not 
requiring to know that here you have to do A,B,C and there only A and 
there A and B

On the other hand isn'tt that in some sense a generalization of the 
engine setup (ie checkengine)?

that is: couldn't we have one or more config files (in the main dir), 
maybe anything ending in .config and if those exist each of them defines 
a config (including testdirs, engines, what have you) and by default 
they are all run

on the same time you could restrict yourself to run only A.config by 
supplying check -c A or check -c A,B

just a thought

**Comment by blefloch** [comment]
Frank's solution seems good: loop over test directories, loop over config files, and call for each config file whatever function does the checks or saves.

**Comment by FrankMittelbach** [comment]
Am 04.07.2017 um 20:30 schrieb Bruno Le Floch:
> Frank's solution seems good: loop over test directories, loop over 
> config files, and call for each config file whatever function does the 
> checks or saves.

except that I would (perhaps) put the config files in the main directory 
and loop over them there. Advantage: you can reuse the test dirs (if 
that ever makes sense)  and the configs are all next to each other so 
easy to compare select ...

On the other hand if the confic end up always being tied to one test dir 
in reality then perhaps putting it there makes more sense

**Comment by josephwright** [comment]
@FrankMittelbach  Interesting idea: avoids the need to mess with `testfiledir`, _etc._: I like it. Easiest would be something like
```lua
testconfigs = {"config-TU", "config-plain"}
```
where we require each to match a `.lua` file in the main dir (I thought about omitting the `config` but probably it is better to insist on that part). As you say, each one can then call `build.lua` as appropriate, probably _via_ a new option (so 'behind the scenes' we do `--config config-plain`, `--config config-TU`, _etc.) (Remember we need to keep each run 'isolated' and we can't 'unglobal' the variables.)

So that leaves the questions of what to call the variable behind this and do we require a 'no-op' config (or is that a 'given')? Probably it would be clearer with these more complex cases if every config has to be listed such that an empty table means 'don't look for configs at all: there's only the basic one'.

**Comment by josephwright** [comment]
Perhaps use a `configsdir` rather than list all configs manually? We then just have to look over the dir and run a test for each `.lua` file in it: if it's missing we don't do anything special.

**Comment by wspr** [comment]
That might keep things tidier. Okay by me I think.

**Comment by FrankMittelbach** [comment]
Am 05.07.17 um 08:17 schrieb Joseph Wright:
> Perhaps use a |configsdir| rather than list all configs manually? We 
> then just have to look over the dir and run a test for each |.lua| file 
> in it: if it's missing we don't do anything special.

probably a good idea, as long as the help text lists the configs from 
that dir so that it is easy to do something like -c <config>

and if you put it into its own dir you don't need any requirements on 
the config file names I guess

**Comment by josephwright** [comment]
@FrankMittelbach  You mean if you get one wrong, as for `-e` at present? Certainly doable. I'm just sorting a few re-writes of the supporting option stuff at the moment, then should be able to get this done.

**Comment by josephwright** [comment]
@FrankMittelbach  Yes, using a dir avoids name requirements: seemed easiest to me, and it means it's clear if you need the approach at all (no `configdir` value => do nothing special).

**Comment by FrankMittelbach** [comment]
Am 05.07.17 um 10:38 schrieb Joseph Wright:
> @FrankMittelbach <https://github.com/frankmittelbach> Yes, using a dir 
> avoids name requirements: seemed easiest to me, and it means it's clear 
> if you need the approach at all (no |configdir| value => do nothing 
> special).

agreed

and yes, getting a listing of available configs if you ask for one that 
is not there (or you ask via -c without supplying a config  seems like a 
useful interface to me

**Comment by josephwright** [comment]
I've added initial support but I'm not sure about how to handle the 'vanilla' config (if we want one to exist). Does
```
texlua build.lua check
```
with one config file run first without loading it then with, so `build.lua` contains 'vanilla' options, or do we perhaps want to say that with multiple configurations *every* case has to have a config file? The latter is in some ways easier as it means that
```
texlua build.lua check -c <config>
```
is _always_ possible, but means that
```
texlua build.lua save <name>
```
needs a config: perhaps add a `stdconfig` variable to deal with this.

Notice that at present I've treated `-c` as a simple string so you can give exactly one value: do we want a comma list (table) as for `-e`?

**Comment by josephwright** [comment]
New implementation treats `-c` like `-e`: it's a table of possible configs.

**Comment by josephwright** [comment]
Fixed in https://github.com/latex3/l3build/pull/38.
