### ISSUE TITLE
Renaming master branch

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#180]
In common with many other projects (and following the changed default
branch name at GitHub) we  plan to rename the "master" branch to "main"

GitHub will redirect any pull requests from forks to the "master" branch but
once the rename is done it would be better if any local clones or forks of
this repository renamed their branch to "main".

The following commands will rename the local branch and re-set tracking to the GitHub repository main branch.
This should be done after the rename here.

```
git branch -m master main
git fetch origin
git branch -u origin/main main
git remote set-head origin main

```

**Comment by jlaurens** [comment]
Is there a deadline?

**Comment by josephwright** [comment]
No, no deadline

**Comment by FrankMittelbach** [comment]
but since it is basicaly transparent (even if one has local branches) I don't see much problem with getting it done and over with, or is there any? All one has to do is to locally run the 3-4 lines of code and the rest is nicely handled by the github site

**Comment by josephwright** [comment]
Done
