### ISSUE TITLE
cleandir is dependent on the ordering

### ISSUE THREAD

**Issue by stone-zeng** [latex3/l3build#182]
For example, I need to create and clean the `generic/ctex/zhmap/` dir. However, due to the following code:

https://github.com/latex3/l3build/blob/f0174fee3b19b1faceb3a59b938cef9c144d6a7e/l3build-install.lua#L164-L171

both `generic/ctex/` and `generic/ctex/zhmap/` are created, and the order is not guaranteed. So if `generic/ctex/` is created after `generic/ctex/zhmap/`, the `zhmap` sub-directory will be removed then.

I'm not sure whether the `cleandir()` function should be changed, or maybe we need to normalize the ordering of `paths` in `install_files()`.

**Comment by josephwright** [comment]
I thought we'd looked at this: I'll check back again.

**Comment by josephwright** [comment]
Oh, I remember: I think I didn't get round to going 'all the way' and listing up every path to create in an ordered way. I'll have to think a bit about it.
