### ISSUE TITLE
Convert PDF to PNG and compare PNG files?

### ISSUE THREAD

**Issue by lvjr** [latex3/l3build#187]
I'm writing [tabularray](https://github.com/lvjr/tabularray) package which uses L3 Programming Layer instead of \halign primitive to typeset tabulars. From time to time, I change the method to build the tabulars. And I need to make sure that the tabulars **look** the same as before. In this situation, \showbox is not enough. Is it possible for l3build to convert PDF to PNG and compare PNG files? (Maybe simply compare two MD5 sums of the new and old PNG files.)

**Comment by josephwright** [comment]
In principle doable, but we've avoided image comparison for a few reasons. @zauguin added some code that should allow selectable testing outcomes.

**Comment by lvjr** [comment]
I have written some code to implement this feature: [https://github.com/lvjr/ppmcheck](https://github.com/lvjr/ppmcheck) . Just run
````
l3build
texlua ppmcheck.lua
````
will convert PDF to PNG and compare MD5 sums. Also by setting env variable `imgdiffexe`, we can call `compare` program provided by `ImageMagick` to make image-diff files. Add an option `save` to `ppmcheck.lua` will save the new image and md5 files.

No much code and no other dependencies, hope `l3build` would add this feature some day.
