### ISSUE TITLE
latex3 repository: only generate one format when doing l3build save

### ISSUE THREAD

**Issue by blefloch** [latex3/l3build#191]
When running `l3build save m3prop005` for instance in the `l3kernel` directory of the latex3 repository, the slowest part is that it builds all five formats rather than only building pdflatex which will be used to save the tests.  It would be good if such a case could be detected and if l3build only generated the format corresponding to the default engine.

**Comment by zauguin** [comment]
The format building code is specific to latex3 (and 2e), so I think this issue should go there. The [`fast-l3build-save`] branch there has an experimental fix.

**Comment by blefloch** [comment]
It looks good.  Should we merge that branch there, or  do you have more to do?
