### ISSUE TITLE
MANIFEST.md contains erroneous information

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#195]
Running `l3uild manifest` from the Simple Flat example folder creates a MANIFEST.md which reads
```
It is automatically generated with `texlua build.lua manifest`.
```
which is erroneous in that particular case.

A corollary question is the status of `texlua build.lua` calls: supported, supported with restrictions, unsupported?

**Comment by josephwright** [comment]
Corrected: we no longer support `texlua build.lua ...`, only `l3build ...` (which is equivalent to `texlua $(kpsewhich l3build.lua) ...` on a Unix-like system).
