### ISSUE TITLE
Add support for a separate doc source directory

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#2]
Taken from https://github.com/dffischer/latex3/commit/f14c96ef3bc369e9d274b48c02b606ab7a1bc1b9 and the related pull request: for more complex set ups one might want a separate `docfiledir` or similar.

**Comment by josephwright** [comment]
@dffischer I'll look to sort this over the coming few days.

**Comment by josephwright** [comment]
Possibly this will also go with a `sourcedir` to support something like `beamer`:
```
.
+-- base
|   +-- art
|   +-- emulation
|   |   +-- examples
|   +-- multimedia
|   +-- themes
|   |   +-- color
|   |   +-- font
|   |   +-- inner
|   |   +-- outer
|   |   +-- theme
|   |   |   +-- compatibility
|   +-- translations
|   |   +-- dicts
|   |   |   +-- translator-basic-dictionary
|   |   |   +-- translator-bibliography-dictionary
|   |   |   +-- translator-environment-dictionary
|   |   |   +-- translator-months-dictionary
|   |   |   +-- translator-numbers-dictionary
|   |   |   +-- translator-theorem-dictionary
+-- doc
|   +-- licenses
+-- examples
|   +-- a-conference-talk
|   +-- a-lecture
+-- solutions
|   +-- conference-talks
|   +-- generic-talks
|   + short-talks
```

**Comment by josephwright** [comment]
Perhaps worth noting that we have this split for LaTeX2e,but there it's currently handled by having the two as entirely separate uploads ...

**Comment by dffischer** [comment]
I ported and rebased the original changes to the master of this repository in pull request #27.

A `sourcedir` definitely is a sensible addition. In line with `testfiledir` and `docfiledir` it should perhaps be called `sourcefiledir`. Regarding the structure posted above, the `examples` directory would have to be put into `doc` instead, should a new `sourcefildir` replace collecting files from the local directory `.`.

**Comment by josephwright** [comment]
Fixed by https://github.com/latex3/l3build/pull/36.

**Comment by josephwright** [comment]
Turns out this is much more tricky than I'd first imagined. In a stand-alone package all is fine, but in a bundle (LaTeX3, LaTeX2e), we have issues. I'll need to think about how best to handle this!

**Comment by wspr** [comment]
Ouch, sorry I missed that. I tested only for single-package use — mea culpa!

**Comment by josephwright** [comment]
@wspr  So did I :) I think I know how to fix it, but I'll need to first deal with `moduledir` and make sure it will be orthogonal to `maindir`. I'll do that, and sort the docs, before re-applying the changes I made earlier.

**Comment by josephwright** [comment]
Fixed by https://github.com/latex3/l3build/pull/39.
