### ISSUE TITLE
setting checkinit_hook breaks tests

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#205]
the hyperref build.lua contains a definition for `checkinit_hook ()` and this now breaks the test runs:  the files are unpackage but then the tests don't start.

Removing the function solved the problem. 

I could also reproduce it in tagpdf. A simple

~~~~
function checkinit_hook ()
 print("XXXXXXXXXXXXXX")
end
~~~~

stopped the tests there too.

**Comment by josephwright** [comment]
Did you try with a return value? I think you have to have `return 0` here.

**Comment by u-fischer** [comment]
I did now, and this seems to work. But something must have changed as the tests passed in june at the last hyperref update.

I would suggest to document that a return value 0 (or whatever) is required. Currently the documentation only says that the hook is there.

**Comment by zauguin** [comment]
This change was the fix for #189, there the issue was that errors reported by `checkinit_hook` through the return value were ignored.

Do we want to fix this by updating the documentation or by treating the hook as successful if it doesn't return anything?

**Comment by josephwright** [comment]
The docs do cover this: I think we can close.
