### ISSUE TITLE
`l3build doc` doesn't typeset files from a subdirectory

### ISSUE THREAD

**Issue by niruvt** [latex3/l3build#209]
I have a directory named `test` with the following structure.

```
.
├── build.lua
├── examples
│   └── abcd.tex
└── pqrs.tex
```

My `build.lua` file is like following.

```lua
module       = "test"
typesetfiles = { "examples/abcd.tex", "pqrs.tex" }
```

Both `abcd.tex` and `pqrs.tex` are very minimal with the following code:

```latex
\documentclass{article}

\begin{document}
Hello world.
\end{document}
```

After running `l3build doc`, I get:

```
.
├── build
│   ├── doc
│   │   ├── abcd.tex
│   │   ├── pqrs.aux
│   │   ├── pqrs.log
│   │   ├── pqrs.pdf
│   │   └── pqrs.tex
│   ├── local
│   └── unpacked
├── build.lua
├── examples
│   └── abcd.tex
├── pqrs.pdf
└── pqrs.tex
```

I expected `l3build` to typeset `abcd.tex` too, which it didn't. I don't know what would be the appropriate location for saving the output file `abcd.pdf` (i.e. the `examples/` directory or the `build/doc` directory or both of these), but not compiling the file at all was quite strange. From the above directory structure it is evident that the file was moved to the `build/doc` directory by `l3build`, so it seems like a bug to me that the compilation was not done.

**Comment by niruvt** [comment]
@josephwright this issue still (version  2021-11-24) isn't resolved. Try running `l3build doc` in this project. I tested the exact same steps again given in this issue. Can you please help?

**Comment by josephwright** [comment]
@niruvt  It's fixed in the development version but I've not released that yet - I only adjusted the code yesterday :) It may be a few days before the next release as I'm trying to zap various other bugs.

**Comment by niruvt** [comment]
I am sorry, I thought as you closed the issue and released a new version, the problem must have been solved.

**Comment by josephwright** [comment]
@niruvt  Like most issue databases, we close issues here when a fix gets checked into the sources - releases lag a bit behind. It won't be long - I have another couple of issues I'm trying to pick off, and they may be addressed today.
