### ISSUE TITLE
Replace switch-based selection of PDF (binary) testing with macro approach

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#21]
As raised in #10, the approach of having a `--pdf|-p` switch is probably sub-optimal: replace by something like `\CEHCKPDFBINARY` in the input. The two areas go together but likely this one should be addressed first as parsing the PDF is not required and thus we are here talking about a rearrangement.

**Comment by davidcarlisle** [comment]
I agree that having an in-file flag is better than having a commandline
switch, especially for mixed collections of tests  requiring different
options but I wonder if having some magic comments at the head of the file
rather than a macro might be more flexible, not least to address the issue
of which tex engine and format to use.

**Comment by josephwright** [comment]
@davidcarlisle  I think I've mentioned that before ;)

I guess I see some positives and some negatives. On the positive side, looking for the switch *before* running the tests is a lot easier to implement as we can tell what to do before getting to the 'format the log' stage.

On the down side, we are already formatting logs so there is not an additional file operation. One might also say that all of the testing meta-data can be available to TeX so should be. That can be answered as any special comments can also be macros:
```lua
local makepdf, parsepdfstream
for line in io.lines(lvtfile) do
  if string,match(line, "\\CHECKPDFBINARY") then
    makepdf = true -- Need a PDF
  elseif string,match(line, "\\CHECKPDFSTREAM") then
    makepdf = true
    parsepdfstream = true
  elseif string.match(line, "\\begin%{document%}"} or string.match(line, "\\START") then
    break -- Once we get to the content, give up
  end
end
```

**Comment by josephwright** [comment]
@davidcarlisle  Comments for format would certainly be helpful, though I think I can extend `--testfiledir` to cover this more fluidly than at present (see #18). We've already more-or-less sorted engine variation, though I guess it would be nice if some tests 'knew' to abort rather than needing a macro layer test/marker.

Of course, the other way is to use different file extensions.

**Comment by josephwright** [comment]
Ah, I remember now the difference between `save` and `check`: you already know with the latter how to run the test as there has to be a reference `.tlg` or `.pdf` file. Thus you only need a switch or similar during the `save` target ...

**Comment by josephwright** [comment]
I'm going to wait and see what the feeling is on the nature of the switches: as I say, checking them 'up front' is much easier than in the log (and as they don't have to be looked for during a 'check', it's actually not bad performance-wise).

**Comment by josephwright** [comment]
Based on parallel stuff in https://github.com/latex3/l3build/issues/18, would it be better simply to control this from the `build.lua` side and potentially have three directories/test setups, for example:
- `testfiles` using `.lvt`/`.tlg`
- `testfiles-stream` using `lvt`/`.tpf` ('digested' PDF stream)
- `testfiles-PDF` using `.lvt`/`.pdf` (binary comparison)

So with a variable something like `testmode` with possible values `log`/`stream`/`PDF`?

**Comment by blefloch** [comment]
Are there cases where it's useful to have a single test that is used with two of `tlg`, `tpf`, `pdf`?

**Comment by wspr** [comment]
Nothing comes to mind that *needs* an explicitly synchronised test. With the philosophy that it’s good to test one thing at a time (expl3 tests notwithstanding!) I’d say the use case is rare enough that the developer could duplicate the test in those cases.

Did you have anything in mind?

**Comment by blefloch** [comment]
I had nothing specific in mind, and yes, Will's right that duplicating the tests if needed is most likely ok.

**Comment by josephwright** [comment]
First pass at this in a137f8c39b0e24b2151b5dc90c41a6130ed5432f: there are some issues which I'm still examining, but they are to do with how useful binary tests actually are (so out-of-scope here).
