### ISSUE TITLE
Method to copy/use 'a ready to use texmf source'

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#212]
Working on creating some tests for `pgf` (to help @hmenke) , I've set up https://github.com/josephwright/pgf/tree/l3build-tests. This works fine for tests, but the `ctan` target fails as there are files of the same name in the sources. That happens as they are Lua files: Lua uses the path/name rather than just the name for finding files.

@zauguin has proposed a variable `tdsdirs` in https://github.com/latex3/l3build/tree/direct-copy, but I have a couple of worries

- I don't get how to use it ;)
- I suspect that it's not quite the right approach

My thinking is that where there is a 'ready to use' TDS-style zip that needs to be 'preserved' for release/installation, it's almost always the case that

- DocStrip is _not_ being used, so there is no unpacking
- All of the sources will be 'ready to use'
- Copying those files to the working area is not really beneficial

So I wonder if we might go with a different approach. We have a single switch, let's call it `tdsreadysource`, and _if_ `sourcefiledir` is not equal to `currentdir` we

- Skip any unpacking phase
- Attach `sourcefiledir` as the first entry after `.` in `TEXINPUTS`, etc.
- Set up to copy exactly `sourcefiledir` when installing or building for CTAN

The last point would also mean we skip checking on source, etc., files and just copy-as-is.

Thoughts?

**Comment by u-fischer** [comment]
I'm not sure about the "no docstrip part". The texmf structure in pgf is actually only needed for the lua files, the rest could be flat and could use docstrip. Another example where both exists is psnfss which has a dtx and two zip files with tds-structure.

**Comment by josephwright** [comment]
@u-fischer  'Could use DocStrip' is a long way from 'does use DocStrip'. I suspect anyone making Lua files using DocStrip would have them have different names, so the issue then would go away. My thinking is that people who want 'live-style' sources have their entire project set up that way: `beamer` works much the same, although I nowadays 'flatten' it (I can get away with it there).

Perhaps @zauguin's plan works ... can someone show me how to use it?

**Comment by zauguin** [comment]
> can someone show me how to use it?

Applied to your l3build-test branch you could use
```diff
diff --git a/build.lua b/build.lua
index 9214d81b..3f873e00 100644
--- a/build.lua
+++ b/build.lua
@@ -8,7 +8,8 @@ sourcefiledir = "./tex"
 flattentds = false

 -- Non-standard installation
-installfiles = {"**/*.cfg", "**/*.def", "**/*.lua", "**/*.tex"}
+installfiles = {}
+tdsdirs = {tex = 'tex'}

 -- Nothing to unpack
 sourcefiles = installfiles
@@ -17,10 +18,6 @@ unpackfiles = { }
 -- Use the generic root as-standard
 tdsroot = "generic"

--- Location mapping done by hand to preserve structure
--- This is a long list so we use a separate file
-tdslocations = require("./filemap.lua")
-
 -- For the manual
 docfiles =
   {
```

Basically the variable `tdsdirs` is a dictionary mapping from paths in your source sirectories to locations in the texmf tree it should be copied to, so to cop the `tex` directory to `$TEXMF/tex`, you add `tdsdirs = {tex = 'tex'}`.

**Comment by josephwright** [comment]
@zauguin  Doesn't quite work as it stands - depending on exactly what I do, I get either a failure to compile the docs, or no installed files, or duplicated installed files. It's certainly in the right direction though.

**Comment by zauguin** [comment]
> Doesn't quite work as it stands - depending on exactly what I do, I get either a failure to compile the docs,

That's probably because the TEXINPUTS etc. aren't adjusted. I don't know how much automation is usable here. E.g. if someone uses a directory containing a full texmf tree we probably just want to add prefix it to `TEXMFAUXTREES`, while setups where e.g. only a `tex` subtree is set should only update `TEXINPUTS`. We could try to check for the must common values here, but since this is a special interface I would actually prefer to keep it fully general and leave such adjustments to the user (Especially if we document how to do thay) (Might get complicated with MikTeX though).

> or no installed files,

That's weird. As long as `tdsdirs` is set it should install something (as long as the source dir isn't empty)

> or duplicated installed files.

We could add a new configuration variable to separate which files to install and which files to copy for checking/typesetting, but then we would still copy the files (probably without their directory structure) to some work directory which is pretty much what we wanted to avoid. Also I would want to keep `installfiles` available to allow some files to be traditionally installed, even if some part of the tree is copied as a whole. (I have that situation e.g. in the `fontawesome5` package: Some TeX files which are generated and placed classically and then a separate bunch of font related files placed all over the font directories in texmf)

**Comment by u-fischer** [comment]
> Might get complicated with MikTeX though

registering roots with miktex is quite easy. Simply 

      initexmf --register-root .... 
      initexmf --unregister-root ...


> while setups where e.g. only a tex subtree is set

I think that setups like the lua case need full trees anyway, supporting subtrees sound like a source for confusion and troubles.

**Comment by josephwright** [comment]
> > Doesn't quite work as it stands - depending on exactly what I do, I get either a failure to compile the docs,
> 
> That's probably because the TEXINPUTS etc. aren't adjusted. I don't know how much automation is usable here. E.g. if someone uses a directory containing a full texmf tree we probably just want to add prefix it to `TEXMFAUXTREES`, while setups where e.g. only a `tex` subtree is set should only update `TEXINPUTS`.

We only support `TEXINPUTS` and `LUAINPUTS` at present for e.g. tree isolation, adding support `texmf` files, etc., so I'd start there. If we need more entries, we should probably make that list of `...INPUTS` into a table we can iterate over.

 > > or no installed files,
> 
> That's weird. As long as `tdsdirs` is set it should install something (as long as the source dir isn't empty)

That might be me messing up the tests: there were a few things I tried that might have simply not made sense.

> > or duplicated installed files.
> 
> We could add a new configuration variable to separate which files to install and which files to copy for checking/typesetting, but then we would still copy the files (probably without their directory structure) to some work directory which is pretty much what we wanted to avoid.

If it comes down to copying the file or not having things working, I think the choice is clear :)

> Also I would want to keep `installfiles` available to allow some files to be traditionally installed, even if some part of the > tree is copied as a whole. (I have that situation e.g. in the `fontawesome5` package: Some TeX files which are  generated and placed classically and then a separate bunch of font related files placed all over the font directories in texmf)

OK, that makes life a bit more fun then.

Sounds like we are in the right direction but need to work out how to cover the various places where the files are needed. Can we arrange to use the `tdsdirs` code to 'install' the pre-built tree into the working area?

**Comment by josephwright** [comment]
> > registering roots with miktex is quite easy. Simply
> 
> Is there a way to do that without changing global state? E.g. purely though environment variables or local configuration files? Registering roots globally seems rather dangerous since interrupting it at the wrong time would leave weird texmf paths in place.

Indeed: all of our current code comes down to

    cd <some place> && set <various vars> && <do stuff>

essentially, so there is no danger of leaving a problematic state.

**Comment by josephwright** [comment]
Almost there: I've got the `check` and `install` targets set up correctly, just have to fix `doc`.

**Comment by josephwright** [comment]
Latest checkins fix `doc` target, just `ctan` now outstanding

**Comment by josephwright** [comment]
Right, I think my issue boils down to `copyctan()`, plus a more conceptual one of how
```lua
tdsdirs = {tex = "tex", doc = "doc"}
```
interacts with installation. (There's also a question of picking out the typeset source file(s) so they don't get duplicated.)

**Comment by josephwright** [comment]
OK, I think things are working modulo one strange message, although there is a conceptual question

@henrimenke I'm not sure if you want to test using this branch and the 'matching' set up in my branch of `pgf`? If you do, you'll need
```
texlua $(kpsewhich l3build.lua) <target>
```

@zauguin Could you take a look at my commits and see if you are happy? I'll track down the one issue I know of, and after that if you and @henrimenke are happy I'll do a release, so it's easier for others to try this feature out.

**Comment by josephwright** [comment]
Ah, yes, the conceptual issue. For the doc typesetting, we need the 'main' source file to be copied by `l3build`. If it's also in a `tdsdirs` location, we end up with it twice in the CTAN distribution files. Suggestions on how to proceed welcome. The obvious one is to say that it should not be in the `tdsdirs` tree, but that probably isn't very 'nice'.

**Comment by josephwright** [comment]
OK, I see the issue - sorting it

**Comment by josephwright** [comment]
Right, I think the CTAN issue is actually nothing to do with `tdsdirs` as such: it's that we don't make the right directories in some cases. That can be fixed separately.

With the current branches here and at https://github.com/josephwright/pgf/tree/l3build-tests, I can successfully build a `pgf` release (of sorts). I'd really like thoughts here: @zauguin, @hmenke, others ....

**Comment by zauguin** [comment]
Could you take a look at my commits and see if you are happy?

I'm very happy with the changes. :)

> Suggestions on how to proceed welcome. The obvious one is to say that it should not be in the `tdsdirs` tree, but that probably isn't very 'nice'.

IMO that's a reasonable requirement. For typical CTAN packages the documentation should end up at the root and it's reasonable to expect the source to be next to the compiled file, so not having them in the `tdsdirs` tree sounds correct. MAybe we could add a hook at the end of `copyctan` to allow the user to move the files around if there are different requirements?
