### ISSUE TITLE
Git support

### ISSUE THREAD

**Issue by niruvt** [latex3/l3build#216]
I love `l3build ctan` and `l3build upload` commands a lot. Can something similar be developed for git projects too?

**Comment by josephwright** [comment]
I am really not sure what you mean!

**Comment by niruvt** [comment]
Sorry for not being clear. I will try to explain and exemplify what I meant.

Let's say I have a git-project named `ltxproject`. I will most likely have a root directory with the following structure.

```
.
├── COPYING
├── ltxproject
│   ├── build.lua
│   ├── ltxproject.dtx
│   ├── ltxproject.ins
│   └── testfiles
│       ├── testfile.lvt
│       └── testfile.tlg
└── README.md
```

A git project hosted on sites like GitLab/GitHub usually requires the README file to be located in the root directory i.e. `ltxproject/` and not `ltxproject/ltxproject`. Some people prefer providing the `.sty` file in the git, while some people don't. What I meant was having a command, like say, `l3build git` to refresh the README file, generate the `.sty` file if a user has requested it in the `build.lua`. Read the list of un-`push`ed commits and push them with an interactive command, like say, `l3build push` (similar to `l3build upload`). If the user wants to push some parts from the build directory too, that too can maybe configured.

Right now I have to manually generate the README by running `pdflatex ltxproject.ins`, delete the `.log` and `.sty` generated by the process. Move the README from the embedded directory to the root directory. I think it would be much better if this could be automated.

**Comment by niruvt** [comment]
Correct me if I am wrong, but I think right now there is no way to generate sty or README with `l3build`. I know we can find them in the `build/unpacked` directory, but again, they are not where they should be.

**Comment by davidcarlisle** [comment]
@niruvt  it isn't very clear what issue you see (as you know almost all the latex project l3build propjects are using git/github).

It seems an anti-pattern to check generated files in to git. Normally the README is directly edited as source not generated, l3build supports either re-using your git project README.md for the ctan submission or using a separate readme file for that (see the ctanreadme variable)  If you do want to generate the CTAN README from the dtx file that should work automatically, .md files are in the default `textfiles` list that is packed in to the ctan zip?

**Comment by josephwright** [comment]
Also note that one can add custom targets already

**Comment by josephwright** [comment]
I think there are at least things here: using an 'all in one `.dtx`' (not something that's useful really with Git, etc.), structuring your sources and direct Git interactions. I'm not seeing any of them as directly requiring changes in `l3build` at the moment.

**Comment by niruvt** [comment]
Thanks both of you for explaining. I understood your point. Sorry for the noise. Closing.
