### ISSUE TITLE
Install files into directories with spaces in their names

### ISSUE THREAD

**Issue by leingang** [latex3/l3build#228]
I am using `l3build` to automate document generation (not package testing or installation). I would like to install the documents in a documents tree rather than in a `texmf` tree.

The workaround I'm using is to set `options['texmfhome']` to the directory I want to install the files in, and `tdslocations` to install any PDFs generated at the top of this directory, like so:

    options['texmfhome'] = '/path/to/install'
    sourcefiles = {}
    tdslocations = {'*.*.pdf'}

This works pretty well, _unless_ the path in the first line leads to a directory with spaces in it.  For instance, if `options['texmfhome']` is set to `/Users/mathew/Public/foo bar', the error I get is:

    cp: /Users/matthew/Public/foo\ bar/.: No such file or directory

I know that spaces in paths have been an issue in the past (e.g., issue #124), and I realize that a “real” `texmf` tree probably shouldn't have a space in its name, but I hope this could be addressed.

**Comment by josephwright** [comment]
Unless @zauguin  or @PhelypeOleinik  fancy it, I guess I need to fix this (or rope @cereda into it!)

**Comment by leingang** [comment]
Thank for you looking into this so quickly! I just installed the new version and it works for me!
