### ISSUE TITLE
"dependencies"

### ISSUE THREAD

**Issue by yegor256** [latex3/l3build#244]
Would be great to have a command that would generate `DEPENDS.txt` file, which is [required](https://tex.stackexchange.com/questions/644386/regarding-the-depends-txt-in-ctan-upload) by CTAN. This file should have a list of packages which my package depends on. The simplest way to collect such a list is by going through `dtx` file and finding all occurrences of `RequirePackage`. Maybe you can suggest even better method.

**Comment by josephwright** [comment]
The tricky part there is that `DEPENDS.txt` is set up for LaTeX packages, rather ones on CTAN/TeX Live. So scanning for `\RequirePackage` wouldn't necessarily work. There's also the fact that Karl wants to split 'hard' and 'soft' dependencies, i.e. those that apply to all load paths and those that are only for some cases. Also, we need to allow for the existing dependency tree (e.g. all LaTeX packages can expects everything in `amsmath`, `graphics` and `tools`). So there's a bit to think about.

**Comment by josephwright** [comment]
Looking back, I really do think this is out-of-scope: working out TL dependencies is not easy, and only really works with a VM to test. So I will close - because I don't think a workable feature is viable
