### ISSUE TITLE
Skip console confirmation of "upload"

### ISSUE THREAD

**Issue by yegor256** [latex3/l3build#247]
I execute `l3build upload` in a [script](https://github.com/yegor256/iexec/blob/master/.rultor.yml), which is run by a machine (not a human being). Now, I have to configure it like this:

```
echo 'y' | l3build upload --halt-on-error
```

Would be much more convenient to have an option for this:

```
l3build upload --halt-on-error --yes
```

**Comment by davidcarlisle** [comment]
see `l3build-upload.lua` you can set `ctanupload` to true and it won't ask

**Comment by yegor256** [comment]
@davidcarlisle I should add `l3build-upload.lua` to my repository? Now I only have `build.lua`.

**Comment by yegor256** [comment]
@davidcarlisle this code inside `build.lua` has no effect:

```
module = "iexec"
uploadconfig = {
  pkg = "iexec",
  ctanupload = true
  ...
}
```

**Comment by yegor256** [comment]
@davidcarlisle this is my config: https://github.com/yegor256/iexec/blob/master/build.lua This is the result of the build (scroll to the bottom): https://github.com/yegor256/iexec/issues/12

**Comment by yegor256** [comment]
@davidcarlisle maybe I'm using some old version of l3build?

**Comment by davidcarlisle** [comment]
@yegor256  sorry you are right 

```
      local ctanupload = ctanupload or "ask"
```

in `l3build-upload.lua`  should not be there, this file is read before your setting so it always sets to `ask`

instead  the end of  l3build-variables.lua should be

```
-- Upload settings
curlexe  = curlexe  or "curl"
uploadconfig = uploadconfig or {}
ctanupload = ctanupload or "ask"
````

with ctanupload line being added.

It then gets set to  `ask` only if not set as that file is read after `build.lua`

@josephwright  does that look right?

Incidentally I had to change 

`  if string.match(file, "%.dtx$")  ||  string.match(file, "%.lua$") then`

to

`  if string.match(file, "%.dtx$")  or  string.match(file, "%.lua$") then`

in your  `build.lua`

I'd also note that we wouldn't normally recommend automated uploads with no confirmation, ctan is not automated so every upload requires human volunteer time to handle the upload and respond, you do not normally want  to do that on every commit for example.

**Comment by josephwright** [comment]
@davidcarlisle  Yes that looks right: I'll adjust

**Comment by muzimuzhi** [comment]
I think this issue has been resolved by
- 223a4ed (Add ctanupload to l3build-variables, 2022-10-02) and
- 8dd0258 (ctanupload set in l3build-variables.lua now, 2022-10-03)

combined.
