### ISSUE TITLE
Fail the build if any LaTeX Warnings have been seen

### ISSUE THREAD

**Issue by yegor256** [latex3/l3build#248]
Would be great to have an ability to fail the build in case of any `LaTeX warning` visible in the output of `pdftex`

**Comment by josephwright** [comment]
That would happen if you've saved you `.tlg` with with no errors and one then arises; I'm not sure of your use case.

**Comment by davidcarlisle** [comment]
@josephwright  I suspect that the request is to treat warings as errors in `l3build doc` It is probably  simpler to handle that at the tex level not as an l3build feature, eg a doc config that redefines 
`\GenericWarning` and `\msg_warning:nnnn` to make errors on a final typesetting run

**Comment by josephwright** [comment]
Agreed: WONTFIX.
