### ISSUE TITLE
how to cleanup between engines?

### ISSUE THREAD

**Issue by yegor256** [latex3/l3build#250]
This is my `build.lua`:

```
dynamicfiles={"_minted-*"}
checkengines = {"pdftex"}
```

Then, I have this `simple.lvt` test:

```
\input{regression-test.tex}
\documentclass{article}
\usepackage{minted}
\begin{document}
\START
\begin{minted}{java}
Hello, world!
\end{minted}
\END
```

Then, I use `l3build save -e pdftex simple` to save the `.tlg` file. Then, I run `l3build check`. Works just fine.

Then, I set this:

```
checkengines = {"pdftex", "luatex"}
```

The test stops working, because (I suspect) `build/test/_minted-*` directory is not deleted between engine runs of one test.

**Comment by muzimuzhi** [comment]
After applying changes below, all checks passed for me.
- In `build.lua`, change `dynamicfiles = {"_minted-*"}` to `dynamicfiles = {"_minted-*/*"}`
- In `build.lua`, add `maxprintline = 2000` (any large number should work, defaults to 79)
- Add a workaround in `testfiles/support/regression-test.cfg` for https://github.com/latex3/latex2e/issues/1008.

A mini project for testing [l3build-gh250.zip](https://github.com/latex3/l3build/files/10857071/l3build-gh250.zip)
```
l3build-gh250
├── build.lua
└── testfiles
    ├── simple.lvt
    ├── simple.tlg
    └── support
        └── regression-test.cfg

3 directories, 4 files
```
------
It seems either the doc for `dynamicfiles` need more clarification, or the behavior of `rm()` can be improved to work for directory globs as well.
https://github.com/latex3/l3build/blob/615b6387b342bd66f50e743f6d8bc7e7290400b4/l3build-check.lua#L776-L779
https://github.com/latex3/l3build/blob/615b6387b342bd66f50e743f6d8bc7e7290400b4/l3build-file-functions.lua#L400-L407

**Comment by yegor256** [comment]
@muzimuzhi maybe it will be beneficial to extend the documentation part related to `dynamicfiles` with extra note about glob pattern that must be used there?

**Comment by josephwright** [comment]
Hopefully my added docs cover it
