### ISSUE TITLE
disable release output in \end{document} when LaTeX is used

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/l3build#255]
To support the change for https://github.com/latex3/latex2e/issues/944 `regression-test.tex` should get something like the following added:
```
%
% We don't want release information showing up in \end{document}
% because that would change over and over again.
% We therefore drop that information from the hook 
% By using a voids relation we can reactivate the code in
% a test by dropping "the testmode" label.
%
% We test for \AddToHook in case the regression-test.tex file is used
% with an old LaTeX or  with a different format.
%
\ifx\AddToHook\undefined
\else
\AddToHook{enddocument/info}[kernel/testmode]{}
\DeclareHookRule{enddocument/info}{kernel/testmode}{voids}{kernel/release}
\fi
```
that update should happen fairly soon, to avoid that test output for other people is changing after the change to LaTeX happened.

**Comment by josephwright** [comment]
Should be sorted: want me to release?

**Comment by FrankMittelbach** [comment]
it should be out before we put out a new -dev release so why not. The expl3.ltx is less important though it would be nice too.
