### ISSUE TITLE
bibtex8 (default bibtexexe) returns > 0 for warnings

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/l3build#260]
The return codes for bibtex8 are nonzero for typical (harmless) warnings, that can happen quite often in bigger .bib files, whereas bibtex always returns 0 in such cases. For example,
```
Warning--empty author and editor in Anonymous:2017:CMS
Warning--empty author in ISO:8859
(There were 2 warnings)
~/GitHub/tlc3-book/booksource @ iMac(frankmittelbach): echo $?
1
```
Both are correct entries and should not fail a typesetting run.

The other return codes for bibtex8 are
```
I couldn't open file name `foo.aux'
(That was a fatal error)

~/GitHub/tlc3-book/booksource @ iMac(frankmittelbach): echo $?
3

I found no \citation commands---while reading file unicodefont.aux
I found no \bibdata command---while reading file unicodefont.aux
I found no \bibstyle command---while reading file unicodefont.aux
(There were 3 error messages)
~/GitHub/tlc3-book/booksource @ iMac(frankmittelbach): echo $?
2
```
while bibtex returns 0, 1, 2 in the three cases.

The bibtex8 returns are more logical, but the issue here is that just testing for 0 doesn't work for bibtex8.

**Comment by josephwright** [comment]
Isn't this a question for BibTeX8? I'm not sure I agree that a warning about a data issue is something you can ignore: it is an issue that needs human intervention: change the `.bib` record, change the `.bst` to account for the data format, etc.

**Comment by FrankMittelbach** [comment]
Not necessarily. At least not with bibtex databases. They do contain entries that will not work without warnings depending on the style you use (or even with most) and you aren't expected to change the .bib file (say, those from Nelson Beebe) just because you use a different bst file.  Case in point: a work that has only an editor but no authors and natbib styles warn in that case, but that is just the way the entry is (and has to be). Basically I know of no warning for which there is a need to take actions most (or even all) of the time and in most cases the entry is 100% correct but some styles are super cautious and warn if certain fields are missing (or both given).

As I wrote I think it is not wrong that BibTeX passes different return codes for  warning error and fatal, but as far as l3build is concerned I think it should be possible to make it behave like BibTeX and not stop the processing. Right now, all I can do to use it with the tlc3 examples is to change to BibTeX (and drop the bibtexops value).

Actually, I'm not even sure that the l3build default of `bibtex8` is the right thing to do. I would probablychange that to `bibtex` by default that as a simple measure or at least document that bibtex8 complains about any warning and processing stops.

**Comment by josephwright** [comment]
Looking back at this, isn't the issue that we can't really know what binary is in use: if we assume that the errorlevel 1 isn't an error, that will apply to both BibTeX and BibTeX8. So perhaps the first step is to try to get them do _the same thing_, so at least we have a clear target?

**Comment by FrankMittelbach** [comment]
Well, perhaps we could have an error_level test depending on the bibtool being used as a set of variables so that the test can behave differently if Biber or bibtex8 or bibtex is used.
Variables so that they can be adjusted but probably hard-wired values would be good enough (right now it is also hard-wired)

**Comment by FrankMittelbach** [comment]
Ah, just saw you handled that differently.
