### ISSUE TITLE
[feature] Can l3build provide shell completions?

### ISSUE THREAD

**Issue by Freed-Wu** [latex3/l3build#261]
Just like

```sh
❯ l3build --<TAB>
option
--date                Sets the date to insert into sources
--debug               Runs target in debug mode
--dirty               Skip cleaning up the test area
--dry-run             Dry run for install or upload
--email               Email address of CTAN uploader
--epoch               Sets the epoch for tests and typesetting
--first               Name of first test to run
...
```

TIA!

**Comment by josephwright** [comment]
Shell completion is down to the shell ...

**Comment by Freed-Wu** [comment]
I am not familiar with lua, but I know python/nodejs/go/rust have some library can generate shell completions for bash/zsh/fish/... :smile:

Like

- https://docs.rs/clap_complete/latest/clap_complete
- https://jmtirado.net/shell-completion-with-cobra-and-go/
- https://docs.iterative.ai/shtab
- https://github.com/f/omelette

Or write manually shell completions for the common shells

**Comment by davidcarlisle** [comment]
You can not do this from within the l3buld lua you would need to specify code for l3build in bash-completions (for bash)  see https://stackoverflow.com/a/49034182/1158383 as such I think this needs to be a  separate installation, l3build is typically just installed as part of texlive and by design the texlive instlall just installs into a single directory tree and just requires the user to set the PATH.

**Comment by Freed-Wu** [comment]
I know l3build is a part of texlive which only be installed to TDS not the root
of file system so it cannot change any file outsided TDS (such as
`/usr/share/bash-completion/completions/l3build`,
`/usr/share/zsh/site-functions/_l3build`,
`/usr/share/fish/vendor_completions.d/l3build.fish`).

I means: can l3build provide a command line option like `--print-completion {bash,zsh,fish}`.
When the user `l3build --print-completion Xsh`, it will output the completion
shell script to terminal,

1. user can `eval "$(l3build --print-completion Xsh)"` in the bashrc or zshrc to get support of shell completion.
2. bash-completions/zsh-completion can provide a shell script like
   `/usr/share/bash-completion/completions/l3build` or
   `/usr/share/zsh/site-functions/_l3build` to `eval "$(l3build
   --print-completion Xsh)"` automatically to get support of shell
   completion without adding any code about l3build to bashrc or zshrc.

Just my 2c. I believe there are many people tired of inputing `l3build XXX` without TAB completion :smile:

**Comment by josephwright** [comment]
We've decided against this
