### ISSUE TITLE
Inconsistent variable name: `ps2pdfopt` vs `ps2pdfopts`

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/l3build#275]
Added in commit b27c8c2 (New "ps2pdfopts" variable, 2020-03-11)

- `ps2pdfopts` (plural form) is used in commit message and doc
- `ps2pdfopt` (singular form) is used in `CHANGELOG.md` and all `*.lua` source files

```bash
$ git switch --detach d1413bd # normalize to "current" HEAD on main
$ grep -rn 'ps2pdfopt' .
./l3build-variables.lua:196:ps2pdfopt    = ps2pdfopt    or ""
./CHANGELOG.md:198:- Option `ps2pdfopt`
./build/unpacked/l3build-variables.lua:196:ps2pdfopt    = ps2pdfopt    or ""
./build/unpacked/l3build.dtx:157:\luavarset{ps2pdfopts}  {""}          {Options for \texttt{ps2pdf}}
./build/unpacked/l3build-typesetting.lua:64:    "ps2pdf " .. ps2pdfopt .. name .. psext
./l3build.dtx:157:\luavarset{ps2pdfopts}  {""}          {Options for \texttt{ps2pdf}}
./l3build-typesetting.lua:64:    "ps2pdf " .. ps2pdfopt .. name .. psext
```

Semantically plural form is better but singular form has better backward compatibility. What do you think?

**Comment by josephwright** [comment]
Good spot; I think go with `ps2pdfopts` and then use `(ps2pdfopt or ps2pdfopts)` (or similar) at point-of-use for back compatibility.
