### ISSUE TITLE
normalization of .enc files with pdftex in texlive 2023

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#284]
in texlive 2023 pdftex loads enc-files earlier:

~~~~
\documentclass{article}

\usepackage[T1]{fontenc}
\begin{document}
blub
\end{document}
~~~~

gives with tl2022 at the end of the log-file

~~~~
 34i,5n,38p,161b,107s stack positions out of 
10000i,1000n,20000p,200000b,200000s
{c:/texlive/2022/texmf-dist/fonts/enc/dvips/cm-super/cm-super-t1.enc}<c:/texl
ive/2022/texmf-dist/fonts/type1/public/cm-super/sfrm1000.pfb>
~~~~

With tl2023 the reference to the encoding file moved up to the place 
after loading the pdftex-map:

~~~~
 [1

{c:/texlive/2023/texmf-var/fonts/map/pdftex/updmap/pdftex.map}{c:/texlive/2023/ 
texmf-dist/fonts/enc/dvips/cm-super/cm-super-t1.enc}] 
(./test-utf8.aux) 
~~~~

I don't know if this will stay (I asked on the texlive list) but currently it breaks  test files as the enc-file is no longer removed:

~~~~
***** .\BUILD\TEST-CONFIG-PDFTEX-23\test-mc-user.tlg
  203:  (tagpdf)                and child 'MC (= realcontent)' is 'not allowed'.
  204:  [1
  205:  ] [2] [3] [4]
  206:  The sequence \g__tag_struct_kids_0_seq contains the items (without outer
***** .\BUILD\TEST-CONFIG-PDFTEX-23\TEST-MC-USER.PDFTEX.LOG
  203:  (tagpdf)                and child 'MC (= realcontent)' is 'not allowed'.
  204:  [1{c:/texlive/2023/texmf-dist/fonts/enc/dvips/cm-super/cm-super-t1.enc}
  205:  ]
  206:  [2] [3] [4]
  207:  The sequence \g__tag_struct_kids_0_seq contains the items (without outer
*****
~~~~

**Comment by josephwright** [comment]
No sign of a change in the binaries: I guess we need to find a way to deal with this ourselves?

**Comment by FrankMittelbach** [comment]
looks like it. Guess nothing much possible other than accepting that some tlgs need regenerating directly once TL23 is out. I doubt that could be normalized away and even than tlgs will change at least once.

**Comment by FrankMittelbach** [comment]
I guess he always checks the first time a font is used rather than keeping track of whether a it was already checked for a particular font the moment a fake space is requested. We could ask him if it would be possible avoid that to as long as no fake space isa asked for, but I  guess the coding is simpler this way for him.

**Comment by davidcarlisle** [comment]
@josephwright  I just checked all tests in latex2e/tools and several tests were failing due to this and all now pass

**Comment by josephwright** [comment]
I think we are OK to close here now: may be dependent on the plans for `maxprintline` ...
