### ISSUE TITLE
Skip `build.lua` for certain file list variables

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/l3build#286]
From discussion in https://github.com/latex3/latex3/pull/1179#discussion_r1118572774.

In an ideal world, only `build.lua` files that play the role of default config files should be skipped.  For example, a `build.lua` in `supportdir` should survive.

**Comment by josephwright** [comment]
We need a spec on exactly how this should work - for example, is it all file lists, is there an opt-out, etc.

**Comment by josephwright** [comment]
I think this can be fixed using `excludefiles`: hopefully fixed
