### ISSUE TITLE
Are variables `os_cmpexe` and `os_cmpext` still in use?

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/l3build#300]
Introduced in 4d9885b (Only quote path on Windows if spaces are present, 2018-10-25), now variables `os_cmpexe` and `os_cmpext` are not used in source code.
```
$ grep -rn --exclude-dir=build 'os_cmp' .
./l3build-file-functions.lua:133:os_cmpexe  = getenv("cmpexe") or "cmp"
./l3build-file-functions.lua:134:os_cmpext  = getenv("cmpext") or ".cmp"
./l3build-file-functions.lua:142:  os_cmpexe  = getenv("cmpexe") or "fc /b"
./l3build-file-functions.lua:143:  os_cmpext  = getenv("cmpext") or ".cmp"
```
https://github.com/latex3/l3build/blob/e31b220c342d624f2c80e19eeb62db3dd798c19d/l3build-file-functions.lua#L133-L143

**Comment by josephwright** [comment]
I think they can go
