### ISSUE TITLE
ctan zip files may have a dangerous name

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/l3build#31]
Just a minute ago I made a big blunder and (beside my stupidity) I partly blame l3build.
At the moment `texlua build.lua ctan` generates a zip file in the name of the bundle, e.g., `latexbug.zip` but if that zip is opened on OSX the OS is automatiallly generating a directory from it, thus you end up with `latexbug` inside `latexbug`. This makes it easy to delete the wrong dir or get confused in other ways.

Maybe its better to call these zip files `<module>-ctan.zip` or something like that

**Comment by davidcarlisle** [comment]
I'm not sure ctan can handle a name change  there (or at least not without
some changes at their end)

https://www.ctan.org/help/upload-pkg

says the name should be "xxx.zip where xxx is the name of your package")

**Comment by josephwright** [comment]
As @davidcarlisle  says, the zip name is as-required by CTAN: I never had an issue deleting files when I was on OS X.

**Comment by FrankMittelbach** [comment]
Answer from the CTAN maintainers:
> 
> I assume you are talking about the zip files for uploads,
> _not_ about  ctan:/macros/latex/required/latexbug.zip on
> the archive.
> 
> If that is so, the quick answer is:  Yes, you may well name it
> latexbug-ctan.zip.  A number of authors handle it like that.
> Maybe they have the same sort of problem.

so they don't have a problem with the external file name being different, so it could be

`ctan-<package>.zip`

or something

**Comment by josephwright** [comment]
This is an easy one to implement so we probably should: the only question is the interface to use. We could either have a new variable _or_ a function that returns an 'appropriate' name from the CTAN package input. Typically we go for the former so perhaps `ctanzip = ctanzip or ctanpkg`?

**Comment by josephwright** [comment]
Looking again at this ... should this be a config setting or something that the user applies as they use `l3build`? Feels like it might be a 'local' requirement.

**Comment by FrankMittelbach** [comment]
Isn't `ctanpkg` the name under which the package should appear on ctan? In which case it is nothing that somebody could change just to get a different zip name. Personally I think it would be nice to have a variable for the zip name, i.e. `ctanzip = ctanzip or ctanpkg .. "-ctan"` so that the zips by default have a distinctive name. Not sure @josephwright  what you mean by a a 'local' requirement, local to me or to OSX users or ...?

**Comment by josephwright** [comment]
@FrankMittelbach 'Local' to OS X, I guess, but there is no harm in adding another variable. I'll do that for today's release.

**Comment by wspr** [comment]
@FrankMittelbach — you're right, `ctanpkg` might currently only be used to generate the zip file name but with David's work on uploading packages it should actually be the correct CTAN name for the package.
