### ISSUE TITLE
Remove shebang in build.lua

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#321]
Apparently `texlua build.lua ...` support is dropped down since 2021, the first line of `build.lua` is then misleading and should be replaced by something related to `l3build <command>`.

**Comment by josephwright** [comment]
Sorted

**Comment by muzimuzhi** [comment]
`texlua build.lua ...` is still supported and used when testing `l3build` itself, for example in workflow files in current repository.

https://github.com/latex3/l3build/blob/bbe66f5d8f9427a7d8014b5fad9e09c7bf201c01/.github/workflows/main.yaml#L26-L27
https://github.com/latex3/l3build/blob/bbe66f5d8f9427a7d8014b5fad9e09c7bf201c01/.github/workflows/deploy.yaml#L28-L29

So what @jlaurens meant "dropped" was usage `./build.lua ...`?

**Comment by josephwright** [comment]
> `texlua build.lua ...` is still supported and used when testing `l3build` itself, for example in workflow files in current repository.

Well, `texlua ./l3build.lua`, and as that's purely for developers of `l3build`, I think it's a very niche case :)
