### ISSUE TITLE
Documentation typo

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#322]
The documentation refers to `build-TU.lua` that does not exist in LaTeX2e sources, I suppose it is `config-TU.lua` instead.
Moreover, the corresponding listing is not up to date.
This `config-TU` example relies on the command `l3build check --config config-TU`, but no precision is given on the exact context in which this command can successfully run. A footnote on that matter may help.

**Comment by muzimuzhi** [comment]
It seems this issue is not fully resolved yet.

> Moreover, the corresponding listing is not up to date.

I proposed PR #339 to address this.

> This `config-TU` example relies on the command `l3build check --config config-TU`, but no precision is given on the exact context in which this command can successfully run. A footnote on that matter may help.

Not sure which "context" you meant.

**Comment by jlaurens** [comment]
The context:
0) starting with a sufficiently recent distribution
1) retrieve the latex2e source
2) cd to the `base` folder
3) run `l3build check...`

**Comment by muzimuzhi** [comment]
I still don't get it. I see the `config-TU.lua` example a demo showing how to set configurations for a second set of tests, hence there's no need to introduce precise requirements and steps on how to actually check with _the_ `config-TU.lua` config file in latex2e repository.

The use of `--config/-c <config1>[,<config2>]*` is already introduced in the last paragraph of that subsection, titled "Multiple sets of tests".

Maybe you want to add something after the last paragraph, like "For example, in the directory where `config-TU.lua` lives in, you can then use `l3build check -cconfig-TU <name(s)>` and `l3build save -cconfig-TU <name(s)>` to check and save tests in `testfiles-TU` directory."

https://github.com/latex3/l3build/blob/feb15ccdbee16d8aee501c17c69567eca46ae85e/l3build.dtx#L703-L734

**Comment by jlaurens** [comment]
> Maybe you want to add something after the last paragraph, like "For example, in the directory where `config-TU.lua` lives in, you can then use `l3build check -cconfig-TU <name(s)>` and `l3build save -cconfig-TU <name(s)>` to check and save tests in `testfiles-TU` directory."
> 
> [](https://github.com/latex3/l3build/blob/feb15ccdbee16d8aee501c17c69567eca46ae85e/l3build.dtx#L703-L734)

Exactly, that is a low cost precision that helps a lot. Moreover, people used to test driven development will narrow the checks during development.
