### ISSUE TITLE
Could `l3build check` only test if the compilation is successful

### ISSUE THREAD

**Issue by LogCreative** [latex3/l3build#324]
`l3build check` is a great tool to test if the result has been changed by its regression test mechanism. But sometimes I want to test some comprehensive samples, where some slight changes in the long `tlg` files are not necessary and some modifications are intended which are not necessary to be filed in the version control system. What I only want is if the compilation of the test is successful or not and some obvious changes could be observed by eyes.

I know this could be done by moving the samples to the `typesetfiles` or `typesetdemofiles` so that they could be compiled by `l3build doc`. But it is weird to mix those demo files and the documentation files. And I don't wish to include those samples into the generated package.

It is also hard to come up with a separate script to compile those sample files, since it is hard to sync the generated class or style files in the l3build system. This could bring more complexities on debugging the source code.

Maybe there could be a way to write a custom test type to only test if the compilation is successful?

**Comment by josephwright** [comment]
I think you want `recordstatus`: you can use that, not include `\START` and all that will show up in the `.tlg` is the exist status.

**Comment by LogCreative** [comment]
Thanks for your suggestion! It works. But I want to see the result of engine `xetex` but I find that

https://github.com/latex3/l3build/blob/809e98e5d4e16d75f3ed92cb2474587e9b60f74b/l3build-check.lua#L769-L772

The options will be override in this engine, is there a work around for this?

**Comment by u-fischer** [comment]
> I think you want recordstatus: 

Does that actually work on windows? I just tried and regardless which error (missing input file, undefined command) or not I put into the lvt I always get

~~~~
Compilation 1 of test file completed with exit status 0
~~~~

**Comment by josephwright** [comment]
> Thanks for your suggestion! It works. But I want to see the result of engine `xetex` but I find that
> 
> https://github.com/latex3/l3build/blob/809e98e5d4e16d75f3ed92cb2474587e9b60f74b/l3build-check.lua#L769-L772
> 
> The options will be override in this engine, is there a work around for this?

Not currently, as testing doesn't need the PDF: they just slow stuff down. You can always use `dvipdfmx` manually after crediting an `.xdv` file

**Comment by josephwright** [comment]
> Not currently, as testing doesn't need the PDF: they just slow stuff down. You can always use `dvipdfmx` manually after crediting an `.xdv` file

I say currently as of course we could add some more control here

**Comment by josephwright** [comment]
> > I think you want recordstatus:
> 
> Does that actually work on windows? I just tried and regardless which error (missing input file, undefined command) or not I put into the lvt I always get
> 
> ```
> Compilation 1 of test file completed with exit status 0
> ```

That I don't know: Will wrote that particular piece of code, I've never used it but it came to mind with this question. I'll check it's actually working at all then try to track down any platform-specific problems.

**Comment by josephwright** [comment]
> > I think you want recordstatus:
> 
> Does that actually work on windows? I just tried and regardless which error (missing input file, undefined command) or not I put into the lvt I always get
> 
> ```
> Compilation 1 of test file completed with exit status 0
> ```

Hmm, yes I see that too, at least for tests that give status 256 on macOS. Tricky: this will be down to the binaries I guess, so not in our control. I'll try some manual tests of errorlevel later unless you beat me to it.

**Comment by u-fischer** [comment]
> I'll try some manual tests of errorlevel later unless you beat me to it.

Well if I run `errlevel=os.execute ("pdflatex -interaction=nonstopmode test-utf8")` in some lua file I get 0 or 1 as result depending on if there is an error. So it seems to get lost somewhere later in the process.

**Comment by josephwright** [comment]
@u-fischer  Now fixed I hope - see latest checkin

**Comment by FrankMittelbach** [comment]
> Another alternative (which we use in the base tests if we just want to test for error) is have a normal `` \START`` .... ``\END` but have no actual tests printing to the log, this means that the reference tlg normalised log is essentially empty, but if an error occurs you get an error message in the log and the test fails.

depends a bit on what you define as "essentially empty" I guess. If the document produces any kind of warnings, say low-level overfull/underfull messages then those would show (and possibly change), wouldn't they? Maybe something different to \START could help with that if that sets \hfuzz and \vfuzz and perhaps also disables @latexwarning and a few more so that really only errors would show. Maybe something worth experimenting with to see how well such a scheme works.
