### ISSUE TITLE
Copyright: update manually or automatically by `update_tag()`?

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/l3build#325]
When checking whether latest `l3build` version 2023-12-13-2 (which added back shebang to `l3build.lua` hence will re-enable CI) is obtained by TeX Live, I find the copyright in `l3build.lua` doesn't cover 2023, which seems wrong since `l3build.lua` has been updated several times in 2023.
https://github.com/latex3/l3build/blob/1cae1aa62f94be10c99ffbddfa9851300ec0581d/l3build.lua#L5

Some of the `l3build-*.lua` files have similar problem.

Local tests show that the code to update copyright used by `latex3` repository [in `build-config.lua`](https://github.com/latex3/latex3/blob/76104b03a42246726556384f2ca34083bc6955aa/build-config.lua#L48-L60) works for `l3build` repository too.

Questions:
- Is it ok to add 2023 to copyright notices to _all_ `l3build*.lua` files even if some of them are not updated in 2023?
- Does `l3build` want to keep precise copyright year lists, like
  https://github.com/latex3/l3build/blob/1cae1aa62f94be10c99ffbddfa9851300ec0581d/l3build-help.lua#L3

**Comment by josephwright** [comment]
I think @FrankMittelbach would say go for just a range and cover all the files equally

**Comment by FrankMittelbach** [comment]
Some people view copyright dates as dates indicating in which something has changed, but technically we have the copyight even in year in which we don't do changes. The distinction is only important if the changes are made by different parties and you want to highlight that all changes in  one year are done by person X while in another year changes by Y and Z  have been made, etc , ie you establish individual copyrights. But given that we don't do that here and it is anyway only a formality, I'm indeed for just giving a range (tas long as is reasonable, ie not make a file that is only 1 year old say that it is copyrighted for a whole decade)
