### ISSUE TITLE
Unnecessarily generated formats

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/l3build#33]
When I run `texlua build.lua check -e etex filename` to save time the system still generates all 3 formats (which is really the main time block). Would be great if that generation woul look at the `-e` flag and only generate what is needed.

**Comment by josephwright** [comment]
Easy enough to support: I'll sort it at some stage this week.

**Comment by josephwright** [comment]
Turns out this was already done, but I'd forgotten to keep it in sync with `l3build` changes. Fixed in https://github.com/latex3/latex2e/commit/d5b14a53154341c77c41695b96d7ec8baca4e8da: the issue was specific to LaTeX2e.
