### ISSUE TITLE
Updating `man l3build`

### ISSUE THREAD

**Issue by pablgonz** [latex3/l3build#337]
It would be possible, a cosmetic update, for `man l3build` to reflect more or less the same as `l3build --help`. For example the output of `man l3build` shows:

```
l3build <command> [<options>] [<names>]
```

and `l3build --help` show:

```
l3build <target> [<options>] [<names>]
```

There are also some options that are not documented in `man`.

**Comment by muzimuzhi** [comment]
> There are also some options that are not documented in `man`.

Also `man l3build` doesn't list all commands:
https://github.com/latex3/l3build/blob/a07697feaa4b7776dcccfb7e0d95da8d7c2b868d/l3build.1#L13-L29

**Comment by josephwright** [comment]
I guess this slipped as we mainly use `texdoc`: I'll see what I can do :)

**Comment by josephwright** [comment]
> > There are also some options that are not documented in `man`.
> 
> Also `man l3build` doesn't list all commands:

Well yes, it does say 'most common' - unlike the help, we can't auto-generate the `.1` file.

**Comment by josephwright** [comment]
I've changed the `command` for `target` - anything else in particular needed? The common options all seem to be listed.

**Comment by pablgonz** [comment]
Missing from `target`:

```
   ctan         Create CTAN-ready archive
   manifest     Creates a manifest file
   upload       Send archive to CTAN for public release
```

Missing from `options`:

```
   --debug                Runs target in debug mode
   --dirty                Skip cleaning up the test area
   --email                Email address of CTAN uploader
   --file|-F              Take the upload announcement from the given file
   --full                 Install all files
   --help|-h              Print this message and exit
   --message|-m           Text for upload announcement message
   --show-log-on-error    Show the full log of the failure with 'halt-on-error'
   --show-saves|-S        Show the invocation to update failing .tlg files
   --version              Print version information and exit
```

And I think this option does not exist or was renamed:

```
       --pdf|-p
              Check/save PDF files
```

**Comment by josephwright** [comment]
I've copied the standard info from `l3build --help` into the man file - hopefully that covers it?
