### ISSUE TITLE
Output on failure does not help

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#341]
From latex3/latex2e/base, if you run
```
l3build check -epdftex -cconfig-TU
```
the output reads
```
! Error: Engine "pdftex" not set up for testing with configuration "config-TU.lua"!
```
If you run all checks 
```
l3build check -epdftex
```
l3build ends with
```
Failed tests for configuration "config-TU":

  Check failed with difference files

```
but the list is empty: this message is not really helpful. Repeating the above error would be more appropriate.

**Comment by muzimuzhi** [comment]
With l3build 2024-05-27, the two cases both give a (non-error) message:

```
Skipping unknown engine pdftex
No applicable engine requested, config ignored
```

Related commit: 8b07e31 (Drop switch --force|-f, 2024-01-18)
