### ISSUE TITLE
Check with `stdengine` only

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/l3build#343]
Useful when a quick check is wanted, especially when the test suite is quite large, e.g., in LaTeX2e base and l3kernel.

- Already discussed in #320 (see "The second is ...")
- Loosely related to #341

Since the `stdengine` may differ across config files, any `l3build check -e <specific-engine>` may fail for some of the configs, as shown in linked issues.

> Perhaps rather than `-e<engine>` we could do with a switch to use only the standard/default check engine (so `--default`/`-d`, or `--standard-engine` or ...)?
> _<sub>Originally posted by @josephwright in https://github.com/latex3/l3build/issues/320#issuecomment-1824076437</sub>_

**Comment by josephwright** [comment]
Yeah, I was thinking along these lines for #341 in particular - either the test should be skipped entirely or (more useful) we should just use the default engine
