### ISSUE TITLE
Sync up documented log normalization rules

### ISSUE THREAD

**Issue by muzimuzhi** [latex3/l3build#345]
From time to time, new normalisation cases were caught and implemented, which make the documented rules outdated, especially the LuaTeX-specific rules, see `texdoc l3build` (2024-01-09), sec. 1.12 "Output normalisation".

The normalisation is coded in [`normalize_log()`](https://github.com/latex3/l3build/blob/3d51aaea98479f7afeb5ae6e66d382106232c27f/l3build-check.lua#L337-L338) in `l3build-check.lua`, especially in its nested functions `normalize()` and `normalize_lua_log()`.

**Comment by josephwright** [comment]
Do you have something specific in mind? Usually changes to normalisation are added to the list

**Comment by muzimuzhi** [comment]
I thought I had several cases, but can't recognize any of them right now. May take more time.

**Comment by josephwright** [comment]
@muzimuzhi  Anything here? Otherwise I'm minded to close as I don't know of any specific change required
