### ISSUE TITLE
Consider multiple files for the Lua code?

### ISSUE THREAD

**Issue by wspr** [latex3/l3build#35]
With `l3build.lua` at around 2500 lines, I wonder if it might be time to consider a more ‘literate’ approach to the code. 

But I seem to recall that originally this was not desired since you'd then end up using l3build to unpack l3build. Do we still want to avoid having to munchhausen ourselves (as Frank would say)?

I guess an alternative might be a pretty-printing module for Lua code, so at least we could navigate the typeset code with some additional structure.

Or I might just be procrastinating from actual work, and the code is fine. Thoughts?

**Comment by josephwright** [comment]
The problem with putting everything in a DTX is that you can't then use `l3build` to unpack itself: bootstrapping is then not possible. Now, one might say 'oh well' and get on with it (so you have to do `tex l3build.ins` before anything else), but this seems a bit awkward for a script that is specifically for installation and testing.

(There's the wider question that comes up from time to time of usefulness of the dtx format, particularly as most people want online docs: specifically for Lua code there is an established approach anyway ...)

**Comment by wspr** [comment]
I can definitely see the argument that you don’t want to have to bootstrap yourself.

Of course we could use multiple .lua files; I don’t know if that has any downside really since we’re not loading l3build in a TeX document so we don’t need to worry about muddying up the console :)

I’d say the LaTeX world has a pretty great track record of code documentation, so I wouldn’t immediately jump to the conclusion that “established” solutions are best practice :) But I can see your point that (a) it would be nice to not have to generate the lua file(s), and (b) it would be nice to also have HTML documentation.

I’ll come back to this some time in the future I think — shouldn’t distract myself too much right now…

**Comment by car222222** [comment]
> (b) it would be nice to also have HTML documentation.

Probably, but pdf is equally good for online use.

If the html “prints nicely” than there may not be much to choose between the two.

Both can be generated from a .dtx file so that way we can easily have both.

**Comment by wspr** [comment]
I've just come across a scenario in which multiple files might be helpful. Basically, it would be nice to load variable defaults early so they can be used in subsequent code in a `build.lua` file. I'm imagining something like:

```
kpse.set_program_name("kpsewhich")
sourcefiles  = {"*.dtx","*.ins","unicode-math-table.tex"}
dofile("l3build-defaults.lua")
...
<more setup code which uses not only `sourcefiles` but `typesetfiles` (etc.) as well>
...
dofile("l3build.lua")
```

Of course, not much code in `l3build.lua` would make sense to run in a separate chunk like this.

Making a change like this is a pretty significant architecture shift, so I'd want to check that any thoughts along these lines makes sense to everyone more generally before even thinking of changing any code!

**Comment by josephwright** [comment]
The aim of the set up at present is that essentially all of the variables can be overwritten as they are
``lua
foo = foo or "default"
```
so hopefully there are very few cases where one needs to mess about. In particular, the `main()` function can be swapped out, which allows for loading `l3build` and having to explicitly run some code to actually do something ...

**Comment by josephwright** [comment]
BTW, I know what you mean about the length and have considered splitting the script: we went for a single unit to avoid issues with bootstrapping and dependencies, but perhaps we should reconsider. Splitting the file but keeping everything as a single package would work I think.

**Comment by FrankMittelbach** [comment]
In my opinion a use case with split files would (if used) only introduce kind of hidden dependencies and such workflows would then later break for people using them if we make changes to the code not realizing that this dependency exists. I don't really think it is advisable to split with intention of using parts of the code or injecting stuff in the middle.

**Comment by wspr** [comment]
Sounds like splitting into files for source code management only is okay. If you like I'll mock something up after I've finished with the manifest business to avoid too many parallel developments.

**Comment by josephwright** [comment]
I guess one could split in the repo and reconstruct in the `build.lua` file (it would be quite easy) ...

**Comment by wspr** [comment]
@josephwright But in the end it doesn't really matter if there are multiple `.lua` files, right? E.g., if we hypothetically have

```
l3build-unpack.lua
l3build-typeset.lua
...
```

and load them all with `dofile()` they'll behave as if it were a monolithic package. It's not like in TeX where you get a whole lot of annoying lines in the log file... (nor that time spent on file access is a concern).

The only thing I'm not 100% sure about is whether we can ensure that only *out* versions of the `.lua` files are loaded.

**Comment by josephwright** [comment]
@wspr  Yes and no :)

Within the `l3build` repo itself, where we can know files are 'here' and no tree searching is being done, we can be sure all of the versions match. The moment will do an installation for wider use that's no longer the case. That's why I was thinking that we'd want to combine the files into one if we went this way.

On a technical note, each Lua file is a separate scope. So for local material (_e.g._ all of the `local foo = global.table.foo` stuff) we'd need to duplicate it between files if they are being handled by `dofile()` rather than by making a monolithic script.

**Comment by josephwright** [comment]
BTW, if we do want to split I guess the structure is something like

- Top level file
- Variables
- Argument parsing
- File utilities
- Checking
- Typesetting
- Release tools (CTAN/TDS construction/setversion/...)

**Comment by cereda** [comment]
@josephwright Personally, I'd favour a minimal set of variables and more functions. The proposed structure seems interesting.

**Comment by josephwright** [comment]
@cereda Not sure I follow: the question here is about whether to split up the existing source, at least in the development repo. The number of variables would be unchanged ...

**Comment by cereda** [comment]
@josephwright I meant that, depending on how the split is done, we should not rely too much on global variables. But that's only a way of seeing things.

**Comment by josephwright** [comment]
@cereda Ah, I see what you are getting at. By 'variables' I meant the documented interface ones for controlling `l3build`, not anything that is managed internally. (There are only a few of those, most obviously the `options` table and things like `sourcelist`, which is very similar in many ways to the `sourcefiles` control variable.)

I guess a split would force a heavy refactor.

**Comment by wspr** [comment]
@josephwright — I hadn't mapped out how a split would be broken down but something like what you suggest makes sense.

To be a little more defensive when loading files in a split layout, we could use code like this:
```
  kpse.set_program_name("kpsewhich")
  build_filepath = kpse.lookup("l3build.lua")
  build_path = string.match(build_filepath,"(.*[/])")
  next_file = kpse.lookup("l3build-manifest.lua",{path=build_path})
```
As long as kpse finds `l3build.lua` in a consistent place I think this overcomes the issue of stray files.

I don't have an opinion yet about whether forcing scope is a good or bad thing...

**Comment by josephwright** [comment]
@wspr  That's quite a good idea :) Would also probably address the question of function scope for `manifest`: with multiple files we can likely have each one a bit longer ...

**Comment by josephwright** [comment]
I think we are likely to need to go this way: things like automated CTAN upload will also need non-trivial amounts of code and a single file will get tricky to manage. What I suggest is that I work through doing the split one part at a time, and we look to refactor each file as it is created, or at least to assign someone to check each over. (For example, we might put the `argparse()` code into a single file, and @cereda can look at it.) Does that sound reasonable? The total work is not too bad as we are not going to rework everything ...

**Comment by josephwright** [comment]
I think we'll merge https://github.com/latex3/l3build/pull/34 as a first step, then do the split of other parts.

**Comment by wspr** [comment]
Agreed!

**Comment by wspr** [comment]
I tried doing the split for `setversion`, and it was fairly painless [ besides some other bugs discovered along the way :) ].

Happy to now proceed in a similar way for the rest of the code using the structure @josephwright proposed above?

**Comment by josephwright** [comment]
@wspr  I'm happy for you to do the split, and I'll work on changing `setversion()` and the like.

**Comment by josephwright** [comment]
@wspr  Probably makes sense for you to do all of the split as we'll get a similar 'style' in all of the files. I guess we'll end up with a pretty short main file: is there a gain in having a single 'load subfiles' function there?

**Comment by josephwright** [comment]
@wspr  With this as a plan, I guess we can both then look over each new file as it gets created: as I've said, probably an opportunity to check for refactoring.

**Comment by wspr** [comment]
Oops, forgot to auto-close this.
