### ISSUE TITLE
global typesetopts is ignored

### ISSUE THREAD

**Issue by jlaurens** [latex3/l3build#351]
global typesetopts is ignored

**Comment by josephwright** [comment]
Can you provide an example? I don't immediately see an issue in the code.

**Comment by jlaurens** [comment]
I found the culprit: typo at https://github.com/latex3/l3build/blob/5bc4936f5fe729bf48a9af6ea59de450969943e3/l3build.lua#L131

**Comment by muzimuzhi** [comment]
There are merge conflicts in #352 which if merged would fix this issue.
