### ISSUE TITLE
name or file in documentation of tex()?

### ISSUE THREAD

**Issue by cfr42** [latex3/l3build#368]
`l3build.dtx`:
```
% \begin{function}{tex()}
%   \begin{syntax}
%     |tex(|\meta{file},\meta{dir},\meta{cmd}|)|
%   \end{syntax}
%   Runs \meta{cmd} (by default \luavar{typesetexe} \luavar{typesetopts}) on the
%   \meta{name} inside the \meta{dir}.
% \end{function}
```
I think `\meta{name}` should be `\meta{file}` in the description. 

Sorry, but I'm not sure how to get syntax highlighting correct for `dtx` here. Using `latex` does the same as my TeX editor: everything is a uniform grey.

**Comment by josephwright** [comment]
Indeed - sorted.
