### ISSUE TITLE
Specify build target arguments (or not) consistently in docs

### ISSUE THREAD

**Issue by cfr42** [latex3/l3build#384]
For `check` we have

> `$ l3build check ⟨name(s) ⟩`

Similar syntax is used for `save`, `tag` and `upload`.

For `doc` we have

> `$ l3build doc`

The explanation does imply `<name(s)>` can be given, since it says what happens if none are specified. But this is not great for quickly checking whether arguments are allowed here, so I'd personally prefer the first syntax to the second, but consistent use of either would be less confusing since it would be obvious you had to scan through the text in that case.

**Comment by josephwright** [comment]
Where are you looking? In the docs, we have `l3build check` then `l3build check <names>`, and `l3build doc` followed by `l3build doc <names>`, etc.

**Comment by cfr42** [comment]
> Where are you looking? 

I'm really, really sorry.
