### ISSUE TITLE
A spurious file, bug?

### ISSUE THREAD

**Issue by niruvt** [latex3/l3build#405]
TeX Live 2024 (fully updated) on GNU Linux.

I have the following directory structure:

```txt
.
├── build.lua
├── foo.dtx
├── foo.ins
└── README.md
```

The `build.lua` is as follows:

```lua
module              = "foo"
tdsroot             = lualatex
tdslocations        = {
  "doc/lualatex/foo/*.md",
  "doc/lualatex/foo/*.pdf",
  "tex/lualatex/foo/*.sty",
  "source/lualatex/foo/*.dtx",
  "source/lualatex/foo/*.ins"
}
```

Strangely,

```bash
l3build ctan
```

results in the following at `build/distrib/tds/doc/`:

```txt
.
├── latex
│   └── foo
└── lualatex
    └── foo
        ├── foo.pdf
        └── README.md
```

`latex/foo` has the same content as `lualatex/foo/README.md`. This can be checked with the attached zip.

[test.tar.gz](https://github.com/user-attachments/files/18034379/test.tar.gz)

**Comment by muzimuzhi** [comment]
`tdsroot` should be a string.
```diff
-tdsroot             = lualatex
+tdsroot             = "lualatex"
```

As `lualatex` is undefined/`nil`, `tdsroot = lualatex` only sets `tdsroot` to `nil`, thus the default value of `tdsroot`, `"latex"` is used.

**Comment by niruvt** [comment]
Thanks @muzimuzhi for the quick correction. Sorry for the noise.
