### ISSUE TITLE
Standardise use fo 'check'/'test'

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#41]
Currently the variables used for running the `check` and `save` targets have a mix of names: some are `test`, some are `check`. The latter predominates but `testfiles` is a very long-standing name for the place holding `.lvt` files ... we should though look over these and tidy up.

**Comment by josephwright** [comment]
I suspect everything except perhaps `testfiledir` should be `check...`.

**Comment by josephwright** [comment]
Probably this is easy enough: `testsuppdir` can almost certainly be renamed, as can `testdir` (it's basically internal anyway).

**Comment by blefloch** [comment]
On 12/14/2017 03:55 AM, Joseph Wright wrote:
> Probably this is easy enough: |testsuppdir| can almost certainly be
> renamed, as can |testdir| (it's basically internal anyway).
> 

Perhaps it might make sense to call "test" the variables that are used
by both the "save" and "check" targets and call "check" those that are
only used by "check"?

**Comment by josephwright** [comment]
@blefloch  Did occur to me: just a shame that we mainly call them `check` at the moment. (Everything is needed for both targets.) I guess we could change them all and I can add a temporary compatibility layer with a deprecation date (it's just a question of doing `checkfoo= testfoo or checkfoo` for each variable).

**Comment by josephwright** [comment]
I guess I need to see what others think: it's a trivial change code-wise ...

**Comment by wspr** [comment]
For reference, the current variables are:
```
checkfiles         = checkfiles         or { }
checksuppfiles     = checksuppfiles     or { }
checkdeps   = checkdeps   or { }
checkopts   = checkopts   or "-interaction=nonstopmode"
checkengines = checkengines or {"pdftex", "xetex", "luatex"}
checkformat  = checkformat  or "latex"
  checksearch = true
  forcecheckepoch = true
checkruns    = checkruns    or 1

testfiledir = testfiledir or "testfiles"
testsuppdir = testsuppdir or testfiledir .. "/support"
testdir     = testdir    or maindir .. "/build/test"
```

I can see the argument to use "test" for the files themselves and "check" for the actual save/check processes. If we wanted to keep that we'd want to change:

* `checkfiles` → `testfiles` 

Wait... what is `checkfiles` actually for? To me it looks like `checkfiles` and `checksuppfiles` do the same thing.

**Comment by josephwright** [comment]
@wspr `checkfiles` are derived from the sources by unpacking, `checksuppfiles` come from `supportdir`

**Comment by FrankMittelbach** [comment]
seems to me that all the variables pointing to directories are called 
"test"something and all the variables denoting objects in the process 
are called "check"something

The only oddball in some sense is the directly name (not the variable 
for the directory name) being called "testfiles" on the hard drive by 
convention.

Am I getting this wrong?

Assuming we leave the hard-disk name alone (which I wouldn't touch as 
that is kind of a communicated interface/setup), then what exactly do 
you think needs changing?

**Comment by wspr** [comment]
@josephwright Oops, I confused myself somehow when I was looking at that. I don't *think* any changes are needed here then.

**Comment by josephwright** [comment]
Agreed: we'll close as reviewed-and-OK.
