### ISSUE TITLE
Add an 'uninstall' target

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#43]
For reversing `install`, it would be sensible to allow a quick unininstall. Links to some extent to #6.

**Comment by FrankMittelbach** [comment]
Would it make sense to have a dry run capability for both install and uninstall? I.e. one that simply tells where it would place stuff or delete stuff? (might be too difficult with recursive setups to be worth doing)

**Comment by josephwright** [comment]
@FrankMittelbach All quite doable: one just has to redirect the copy step. I'll open a separate issue for that.

**Comment by josephwright** [comment]
@FrankMittelbach  For `uninstall` I did wonder if one should have to say 'definitely do it' (akin to `git clean -f`), but as we are talking about stuff that presumably can be regenerated, I hope it is safe enough to 'just do it'.

**Comment by josephwright** [comment]
BTW, sorry for the delay on this and other `l3build` tasks: I should find the time at the weekend for them. (They are all relatively small tasks.)
