### ISSUE TITLE
What order do tests run in?

### ISSUE THREAD

**Issue by wspr** [latex3/l3build#46]
I've noticed that tests seem to run in pretty random (but sometimes repeatable) orders. E.g., my last `check -H` started out:

```
Running checks on
  input-fullwidth
  active-sscripts-amsmath
  mathsizes
  operatorname
  lmdefault-mathrm-it-bf
```

But I've just re-run it and received the same (unordered) order.

I quite like the idea of randomising the tests since it means if you're re-running the test suite a lot to fix up a number of changes, you're more likely to catch failures earlier since you don't need to need to sit through the last N tests that have already passed.

OTOH I would also like to be able to force a certain test (or group of tests) to go first, since if the package doesn't even load without error then there's not much point testing more subtle parts of the code.

Is this anything that has been ‘designed’? If we decide to make changes, any thoughts on whether a fixed or random order would be better?

**Comment by josephwright** [comment]
At present, there is no sorting in `l3build` of the test list: we simply take the file list as returned by the OS. In most cases that comes out in some logical (alphabetical) order, but I've notice that for example when running Ubuntu as a VM on top of Windows I get a different order, presumably as there is some low-level oddness with a virtual filing system. There's no reason we can't add a sorting step to the iteration, other than I suppose we then get in to localisation business ...

**Comment by wspr** [comment]
If anything, I’d argue for more randomness! With maybe a hard-coded flag that tests starting with "00-“ go first. Nothing needs to be looked at urgently here; just a reminder for me mostly…

**Comment by josephwright** [comment]
@wspr I'm not sure what 'more randomness' means here!

**Comment by wspr** [comment]
Right now on macOS I get a consistent unordered ordering. I think I’d rather have an actually random order each time. Then we don’t need to worry about localisation for sorting :)

**Comment by josephwright** [comment]
@wspr  Strange: when I was on macOS I got the same order as on Windows. As I say, though, this is down to the OS I think. Probably the best would be to add `table.sort` in the right place, so we get the same order irrespective of OS (doesn't have to be localised: just predictable).

**Comment by blefloch** [comment]
I think you are talking past each other.

- The order is likely whatever the file system gives, so it's not too
strange that different OS's would agree.

- Joseph wants to sort.

- Will wants a random order, to avoid the situation (which happens quite
regularly) of running the test suite, finding that a testfile fails so
fixing it, running the test suite again in the same order (thus
repeating the same work) until the next failing test, etc.  Randomizing
the order every time should speed things up.  For N tests with k failing
tests uniformly distributed I _think_ the current approach gives an
average time N(k+1)/2 and a randomized approach would give
N/k+N/(k-1)+...+N/1 ~ N log(k).

**Comment by josephwright** [comment]
@blefloch I don't know about you, but if I've just 'fixed' something I want the tests to rerun so I find out that I actually have!  If we want to avoid 'redoing the work', we'd be better having a 'start from' option with a defined ordering, surely? (I only use `check -H` where I'm working on there being a reasonable basis that everything should pass, _e.g._ after I've been through and checked each part of `l3trial` by hand, I do a `check -H` at the top level.)

**Comment by josephwright** [comment]
I guess I _like_ having a predictable order of tests, so I know where I am up to. If we do want to look at this again, we might add an 'M of N' counter to the output, e.g.
```
Running checks on
  siunitx-number (1/4)
  siunitx-sansmath (2/4)
  siunitx-table (3/4)
  siunitx-unit (4/4)
```
which if we are manipulating the entire table of tests is easy enough (whatever ordering we go for).

We could compromise on an option for ordering: `--order=random|sort` or similar.

**Comment by davidcarlisle** [comment]
I like the predicatble ordering (on cygwin I always get alphabetic order as
far as I can tell) apart from anything else I know that if i come back and
see the vlatex.. tests scrolling past, it's nearly finished:-)

**Comment by wspr** [comment]
Hmm, let's skip adding a feature (randomness) for the time being instance... I think (a) sorting, and (b) an `(M/N)` indicator to the tests would be enough for me.

**Comment by blefloch** [comment]
On 01/07/2018 09:51 AM, Will Robertson wrote:
> Hmm, let's skip adding a feature (randomness) for the time being
> instance... I think (a) sorting, and (b) an |(M/N)| indicator to the
> tests would be enough for me.

That wouldn't solve your initial problem.  It seems you need (c) a way
to start at a given test.  Then neither (a) nor (b) are essential.

**Comment by josephwright** [comment]
If I add the sorting, adding a randomization switch is easy enough (I just need to look up the best way to 'shake' a table). The marker stuff is also very easy.

Once @wspr merges the file split I'll do this :)
