### ISSUE TITLE
Proposal: something like a `saveall` target

### ISSUE THREAD

**Issue by wspr** [latex3/l3build#48]
When working with unicode-math and friends, I find there's a lot of iteration that happens with the test files since I need to test things that can't be easily checked programmatically so there's a lot of box checking. Even with various LaTeX3 testsuites we have situations where we log a fair amount of material in the TLGs themselves which need a bit of work to correct when making certain types of changes to the code.

At the moment, this is done in a fairly tedious way of either:

* Running `check -H`, stopping on an error, then running `save testXYZ`, then going back to `check -H` which re-runs a lot of unnecessary tests before getting back to where we were. Then iterate. 

Or:

* Running `check`, getting a list of diffs, cross-checking them and running `save testXYZ`, `save testYZA`, ... . Which doesn't sound so bad unless you accidentally lose track of which tests you were supposed to be interrogating. Or if I simply change some internal logic in my package that changes an innocuous part of the log file that's included in each TLG file, I need to manually run `save` on each test file.

It occurred to me that there's a better way since we're now all using version control. If we had a target `saveall`, which operated like `check` but saved TLG files as it went, we could then use the natural diff tools provided by the version control system to see what had changed. It wouldn't be a dangerous operation since the changes aren't permanent unless they're actually committed. Nonetheless I'd still think to implement something like this with a prompt such as "Are you sure? Type "Yes" to proceed."

Personally, I think this would be a huge improvement to the usability of unit testing. But I seem to remember this topic has been brought up before and the idea wasn't popular in the past. Given the inspiration that version control changes the context of how this would be used, are there any objections to me looking into adding a new target to re-save all test flies?

**Comment by davidcarlisle** [comment]
actually I rarely use `save` as check leaves the proto-tlg file as
foo.luatex.log or whatever (it's the file it diffed against the tlg) so if
a check fails and I want to classify it as a pass I just move the .log file
from the test area  into testfiles/.tlg  (but an option to do that wouldn't
be a bad thing, I agree)

**Comment by josephwright** [comment]
There were a couple of reasons we didn't go for `saveall` (or `save --all`). The first was the conceptual: you should be actively deciding to update test files. I can see that this is a somewhat debatable point.

The second aspect is more practical: dealing with engine variants. As @davidcarlisle  has noted, running `check` does leave a file around that one can simply copy in the case of a failure. However, there is the issue that you need to cover a change of the 'standard' test which then may or may not need to have engine-specific variants. I guess one can cover that by doing

1. Running `check` for the standard engine
2. Using the formatted `.log` files to make new standard `.tlg` files
3. Running `check` for all other engines
4. Again using the formatted `.log` files to make engine-specific `.tlg` files

That is of course more-or-less what I (at least) end up doing now, except the `.tlg` files get updated by doing a separate `save` run for each failure (which I do by taking the list of failures, doing a bit of editor work to make it into a long list and then doing a single `save` run for all of the names). So in that sense it's much of a muchness.

One thing I do notice is you say about a change in internal logic with a knock-on to all `.tlg` files. Assuming you mean something like a change of standard text, I'd handle that by manually editing the `.tlg` files then re-running the tests: I know then that I don't have to check every line of every diff as I've accounted for a specific alteration.

I've no strong objection to going this way: perhaps as you say a `saveall` target is better than having this as an option for `save`.

**Comment by josephwright** [comment]
Looking at the code, probably all of that can be covered by splitting `save()` into a couple of parts: the outer wrapper and the inner 'payload'. The 'payload' then just has to get looped slightly differently for the case where all of the tests are to be saved. Points (perhaps) toward `save --all`?

**Comment by josephwright** [comment]
I think we've covered this with the `-S` switch.

**Comment by muzimuzhi** [comment]
`--show-saves / -S` only lists the needed `l3build save` commands, which might be helpful when spotted in a CI log, but what's really needed on developers' own machines is to automatically run those commands, or, automatically save changed test outputs.

For example, `latex2e` maintains several bash scripts to run `l3build save -c<config> <full list of names>`, which does exactly what the proposed new `saveall` target or new `save --all` option does. Thus I think support for some sort of auto saving is welcome.

**Comment by josephwright** [comment]
> For example, `latex2e` maintains [several bash scripts](https://github.com/search?q=repo%3Alatex3%2Flatex2e+path%3A*.sh&type=code) to run `l3build save -c<config> <full list of names>`, 

Well, @FrankMittelbach does! I never use them ;)

**Comment by FrankMittelbach** [comment]
I mean one certainly has to verify each test before putting them into the commit, but with a gui that works pretty nicely and efficiently

**Comment by jolars** [comment]
I for one would also very much appreciate a saveall target or `--all` switch. Sometimes you knowingly make a change that breaks the tests, and in that case it seems fine to me if there were an option to update that all of them, even if that would create an opportunity for someone to shoot themself in the foot. A compromise might be to prompt users for each file that would be updated or a list of all the files (which a switch to turn that off as well (in case a `saveall` target is used). I guess you could also support globbing, which would allow someone to selectively update a set of lists (if properly named).
