### ISSUE TITLE
fc can't open file on Windows

### ISSUE THREAD

**Issue by Stone-Zeng** [latex3/l3build#51]
I use `l3build` to build a test for my project. Both the save and check procedure work well on Lnux ,but they fail on Windows.

The log is like the following:

```
Running checks on
  01-internal (1/3)
FC: cannot open ./BUILD/TEST/01-INTERNAL.XETEX.TLG - No such file or folder

FC: cannot open ./BUILD/TEST/01-INTERNAL.LUATEX.TLG - No such file or folder

          --> failed
```

Then I run (use backslash `\`)

```
fc .\BUILD\TEST\01-INTERNAL.XETEX.TLG .\testfiles\01-INTERNAL.XETEX.TLG
```

I get the correct result. So I guess the problem is from convention between `\` and `/`. I have noticed that there is a `unix_to_win` function in `l3build-check.lua`, but why doesn't it work?

**Comment by josephwright** [comment]
Probably this got overlooked in recent changes: I tend to use `diff` on Windows so don't always look at what `fc` does.

**Comment by josephwright** [comment]
Should now be sorted: fix on the way to CTAN.
