### ISSUE TITLE
Bad argument #1 to require

### ISSUE THREAD

**Issue by moewew** [latex3/l3build#52]
When trying to run `texlua build.lua` on Windows 10 with MikTeX, LuaTeX version 1.07.0 (MikTeX 2.9.6600) I get

```
C:/Program Files/MiKTeX 2.9/tex/latex/l3build/l3build.lua:46: bad argument #1 to 'require' (string expected, got nil)
```

According to `texlua --credits` the Lua version is 5.2.4. `print(_VERSION)` only says 5.2.

**Comment by josephwright** [comment]
Can you take a look inside the file and let me know the version string? (The Lua version doesn't really help that much.)

**Comment by moewew** [comment]
`l3build.lua` says
```
-- Version information
release_date = "2018/01/27"
```
Line 46 is identical to the version on GitHub.

**Comment by josephwright** [comment]
I'll need to check this from my MiKTeX setup (this evening): on TL'17 with LuaTeX 1.0.4 or development 1.0.7 all is fine.

**Comment by moewew** [comment]
Seems to be a problem with MikTeX's `kpsewhich` and LuaLaTeX

The following MWE errors on MikTeX, but is fine on TeX live

```
\documentclass{article}
\usepackage{luacode}

\begin{document}
\begin{luacode}
kpse.set_program_name("kpsewhich")
build_kpse_path = string.match(kpse.lookup("l3build.lua"),"(.*[/])")
tex.print(build_kpse_path)

local function build_require(s)
  tex.print(kpse.lookup("l3build-"..s..".lua", { path = build_kpse_path } ) )
end

build_require("help")
\end{luacode}
\end{document}
```

**Comment by josephwright** [comment]
@moewew  I did wonder: the `kpse` library was the most obvious source of an issue. I guess report to Christian Schenk.

**Comment by moewew** [comment]
So `{ path = build_kpse_path }` is expected to work? `luatex.pdf` seems to suggest so, but I can't be sure.

Is `{ ["-path"] = build_kpse_path }` deprecated?

**Comment by josephwright** [comment]
@moewew  `{ path = build_kpse_path }` works with the TeX Live version, and it matches the syntax described in the manual, so I'd say 'Yes, it's expected to work', at least without some input from Hans _et al._

**Comment by moewew** [comment]
OK. Off I went and complained to Christian Schenk: https://github.com/MiKTeX/miktex/issues/58

**Comment by moewew** [comment]
This was indeed a bug on the MikTeX side that has now been fixed. Sorry for bothering you.
