### ISSUE TITLE
Strange behavior with check and a single file

### ISSUE THREAD

**Issue by FrankMittelbach** [latex3/l3build#53]
Checking a single .lvt file seems to produce a strange error (at least in latex2e/base, I haven't checked elsewhere). Using

```
$ texlua build.lua check tlb-rollback-001
```

gives

```
Running checks on
  tlb-rollback-001 (1/1)
Error: failed to find .pdf, .tlg or .lve file for tlb-rollback-001!
```

even though the .tlg exists and is found if all tests are run

The error doesn't show when I use

```
$ texlua build.lua check --rerun tlb-rollback-001
```

However, in that case the format etc is still regenerated (which I thouhgt is supposed to be omitted if `--rerun`` is used.

Also strange: when using `--rerun` the luatex tlg shows a new difference:
```
(size10.clo
luaotfload | db : Font names database loaded from C:/texlive/2017/texmf-var/luatex-cache/generic/names/luaotfload-names.luc(load luc: C:/texlive/2017/texmf-var/luatex-cache/generic/fonts/otl/lmroman10-regular.luc))
```
The line withluaotfload was not in the file generated earlier with `save -e luatex` and it would be rather unfortunate to have it

**Comment by josephwright** [comment]
I have a feeling I know what the issue is here: some of the internals don't currently 'play' well with `-` in filenames. I'll trace through and fix.

**Comment by FrankMittelbach** [comment]
note that this is really 2 or 3 different (and may be unrelated) issues

**Comment by josephwright** [comment]
On the format-building business, that's currently something of a hack into the script (as it's really kernel-specific): I'd not allowed for skipping it in the `--rerun` step. I guess I can adjust that.

On the LuaTeX cache, I did add some normalisation to try to deal with this: perhaps I've missed some cases. It shows up when a new font gets used: particularly problematic on Travis-CI (it used to need two runs whenever we had a new font used). I thought I'd fixed it ...

@FrankMittelbach  Perhaps best to open two new issues? A good model for us and thus for people beyond the team too :)

**Comment by FrankMittelbach** [comment]
maybe .. initially I thought they are all connected and I didn't want to spam you with bug reports :-)

**Comment by josephwright** [comment]
Ah, I think I was on entirely the wrong track about the basic issue: it's to do with multiple configs. Fix coming up.

**Comment by josephwright** [comment]
I think I've fixed the format-building business in https://github.com/latex3/latex2e/commit/dd18027310a8a22b580550c8b34893713fa65ad6. With the fixes in and an up-to-date `l3build` I'm not seeing any issue with LuaTeX. If there is still a problem, I think it should go down as a new issue.

**Comment by FrankMittelbach** [comment]
well the main issue still remains it seems:

Running
```
Frank@falco MINGW32 /i/Users/Frank/Documents/GitHub/latex2e/base (master)
$ texlua build.lua check -eetex flb-fltrace-001
```
gives
```
Running checks on
  flb-fltrace-001 (1/1)
Error: failed to find .pdf, .tlg or .lve file for flb-fltrace-001!
````
which is obviously not true. (note that I switched back to master)

**Comment by josephwright** [comment]
@FrankMittelbach  Are you _sure_ you have `l3build` from the GitHub repo installed? I've just tried:

- Update `l3build` and `texlua build.lua install`
- Remove the entire `build` dir in `latex2e`
- Ran `texlua build.lua check -eetex tlb-fltrace-001`

and  all seemed well ...

**Comment by FrankMittelbach** [comment]
hmm. done all that, but it still comes out with the error line above at my end. 

(that is on windows) will try later also on the Mac)

**Comment by josephwright** [comment]
@FrankMittelbach  I'll double-check my set up ...

**Comment by FrankMittelbach** [comment]
@josephwright don't!
it is my bloody fault, it is even shown in my comment above, I misspelled the file name (flb- not tlb-) during retesting so  the code is correct to moan -- sorry

**Comment by josephwright** [comment]
@FrankMittelbach  I did exactly the same when testing it out, before realising my error :)
