### ISSUE TITLE
document: \texttt or verbatim

### ISSUE THREAD

**Issue by Stone-Zeng** [latex3/l3build#57]
The `--` in `\texttt{--option}` will be typeset with ligature and becomes a single en dash rather than two hyphens. So using verbatim (or other macro e.g. from `listings`) may be a better choice.

Example:

![default](https://user-images.githubusercontent.com/18233088/36725993-22c5d300-1bf3-11e8-81f5-a42032b17945.PNG)

**Comment by josephwright** [comment]
Oops ...
