### ISSUE TITLE
Copying files with no name

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#64]
As reported in https://github.com/latex3/latex2e/issues/30, current `l3build` releases skip files which have no name 'stem' (just an extension). At least for `.tex` we need to support such names,

**Comment by josephwright** [comment]
Fixed by b59e9a5afb36db7c9c25e290d9fc43aa6d695dd6.

**Comment by aminophen** [comment]
Still I don’t see “.tex” in TeX Live 2018

**Comment by josephwright** [comment]
@aminophen  Sorry about that: the issue is fixed in dev `l3build` but I'd not released that for other reasons. I'll get those fixed today and send `l3build` to CTAN.
