### ISSUE TITLE
disable temporarly output normalisation during a check

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#65]
Would it be possible to have an option to either temporarly disable output normalisation of the log-file (I know that the check than fails definitively) or to keep a backup of the original log-file?  Sometimes when checks fails (or when I create checks) I would  like to see absolute pathes of files and fonts.  Compiling in the testfiles folder is not the same, as support files can be different.

**Comment by josephwright** [comment]
The `.log` files for the last engine run are always available as `<name>.log` in the `test` directory: normally it's therefore enough to simply run with one engine so you get the `.log` you want.

**Comment by u-fischer** [comment]
Ah. Sorry. I only looked at the log-files for the engines and not the other. Thats's exactly what I need.
