### ISSUE TITLE
better control over the set of checks 

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#66]
I have a number of testfiles which are rather sensitive towards system changes. They rely e.g. on local files, fonts or give different results when compiled on windows than on linux. e.g. due to path lengths.

That makes it difficult to use services like travis. Instead of trying to adapt the tests so that they work everywhere or to remove tests that don't work I would prefer to run only a restricted set of checks on travis with the help of some configuration file. At best it would allow to suppress checks for a test only for some engines.

**Comment by josephwright** [comment]
I'm planning to look at some selectivity for test files by having `lvtfiles` or similar as a variable. One possible approach to your use case would be to set a Travis-CI variable and pick that up in the `build.lua` file, and set `lvtfiles` appropriately. Would that work as an interface for you?

**Comment by josephwright** [comment]
I see that this is closely linked to https://github.com/latex3/l3build/issues/49: my feeling is that the two issues can be handled together (if one has a list of test names, one can arrange to exclude names by checking the platform or similar).

**Comment by wspr** [comment]
I’m not sure. For myself I think I would do this with two different build configs, but I can also see the logic here.

**Comment by josephwright** [comment]
@wspr Yes, but if one provides a `testnames`  variable then you can two multiple configs using one `testfiledir`, each selecting only some files. That could mean you have a 'full` config that runs everything and a `travis` config that only runs some tests, for example: you could then arrange that checking on Travis-CI picks the latter, which would then be tests you know don't get messed up by platform-specific stuff.

**Comment by wspr** [comment]
That does seem quite natural, I agree!

**Comment by josephwright** [comment]
@u-fischer Something like
```
if os.type == "unix" then
  excludetests = {"name-1", "name-???" } -- globs
end
```

**Comment by u-fischer** [comment]
Sounds good. Are there restrictions to the glob-syntax? E.g. would `*bbb*` work, and `file[0-9]*` work?

**Comment by josephwright** [comment]
Currently the glob support is 'Windows-like', but the original version of code I've used to convert globs-to-patterns does support ranges too. So I can happily extend the glob support. If you'd rather the names use Lua patterns, I can probably sort that, though it will be a bit more effort.

**Comment by josephwright** [comment]
I'm assuming we are OK here now ...
