### ISSUE TITLE
 luatex checks fail due to differences regarding `(font)` in showoutput after a kern.

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#67]
I have a problem with a test involving luatex.

On my system (windows, TL18, luatex 1.07) a document like this

~~~~
\documentclass{article}
\begin{document}
\showoutput
abc
\end{document}
~~~~

adds `(font)`   behind  the kern:

~~~~
....\TU/lmr/m/n/10 b
....\kern0.28 (font)
....\TU/lmr/m/n/10 c
~~~~

I got two confirmations that this not the case on (all or some) linux texlive, and it seems to be not the case on travis.  And so currently all my builds fails, e.g. https://travis-ci.com/u-fischer/tagpdf/builds/78987833.

I can see that there is some normalisation code in l3build-check.lua but `formatlualog(..)` is not used in my case as I have a `luatex.tlg`. 

Can something be done here? I tried to patch l3build-check.lua but due to the search pathes I can't simply create a local version of the file.

**Comment by josephwright** [comment]
Stock TL should have the same LuaTeX version on different platforms: normalisation _between_ LuaTeX versions is tricky-to-impossible. I've tested your example on (stock) Windows TL (updated today) and on my Linux VM using stock TL'18 (installed today), and as I'd expect, the raw logs show:
```
....\TU/lmr/m/n/10 b
....\kern0.28
....\TU/lmr/m/n/10 c
```
My VM matches exactly the Travis-CI set up, or at least it should do.

Have you got anything non-standard in your set ups?

**Comment by josephwright** [comment]
Further to that, I've cloned https://github.com/u-fischer/tagpdf and run the tests locally: I get failures as my TL'18 LuaTeX doesn't add the `(font)` business. Can you force-reinstall `luatex`?

**Comment by u-fischer** [comment]
Bingo. After quite some testing I found the source of the problem: The newer fontloader I'm using changes the log file, and on travis I got a different log as the fontloader wasn't correctly  included. My last test now passed ;-) (It is a bit surprising that the fontloader affects the output of \showoutput, but it is now too late to try to find out why ...).

**Comment by josephwright** [comment]
On that basis, it's not my fault ;)
