### ISSUE TITLE
l3build always returns 1 when saving

### ISSUE THREAD

**Issue by zepinglee** [latex3/l3build#68]
Here is the minimal example:
`build.lua`:
```Lua
#!/usr/bin/env texlua
module = "l3builderror"
kpse.set_program_name("kpsewhich")
dofile(kpse.lookup("l3build.lua"))
```
`testfiles/test.lvt`:
```TeX
\input{regression-test.tex}
\documentclass{article}
\begin{document}
\START
\showoutput
Test.
\vfil\break
\END
\end{document}
```
I am using TeX Live 2018 on mac with all packages up-to-date. When I run `texlua build.lua save test`, it always returns with 1. Thus it is a problem when I use l3build saving in a Makefile.

**Comment by Stone-Zeng** [comment]
This is due to that the `save()` function in `l3build-check.lua` doesn't return a value explicitly, so it will give a `nil` and let the main function return 1.

**Comment by josephwright** [comment]
Usually we'd expect `save` to be called 'on it's own', but adding a return is easy enough. I'll look at it shortly.
