### ISSUE TITLE
install target should have possibility to include docs

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#69]
As noted in https://github.com/latex3/latex3/issues/384#issuecomment-408773219, `l3build install` doesn't currently include the documentation tree. That could be covered in various ways, for example
```
l3build install --doc
```
(would that include code?)
```
l3build install --include-doc
```
(or `--plus-doc` or ...), or with a variable
```lua
installdocs = true|false
```
or with a separate target (seems a bit excessive).

**Comment by FrankMittelbach** [comment]
I would go for  `install --doc`  (probably with the meaning that it installs code and doc, but just doc is fine too).

**Comment by wspr** [comment]
I think I would vote for `install --doc` compiling the doc and installing it, only. (I guess you could also have `doc --install` but that seems backwards somehow.)

**Comment by josephwright** [comment]
I'll add something and we can see what seems more natural in terms of whether it's 'code plus doc' or 'just doc'.

**Comment by josephwright** [comment]
I think perhaps `--full`, to copy _all_ of the TDS, might be best: short, clear and means we don't also need `--source` at some future stage. Minor re-arrangements of the code should cover this.

**Comment by FrankMittelbach** [comment]
sounds good to me
