### ISSUE TITLE
[Question] how to include demo PDF in the zipfile

### ISSUE THREAD

**Issue by louisstuart96** [latex3/l3build#73]
I'm using TeX Live 2018 on Windows, and have recently updated l3build to the latest version (2018-09-26). 
I'm planning to include some demo PDFs in the documentation (without a main documentation) using a `build.lua` like below:

```lua
module = "..."

sourcefiledir = "./src"
docfiledir = "./doc"

sourcefiles = {"**/*.sty"}
docfiles = {"**/*.tex"}
textfiles = {"*.md","LICENSE"}
demofiles = {"**/*.pdf"}
cleanfiles = {"*.zip"}
unpackfiles = {}
typesetfiles = {}

packtdszip = true
flatten = false

function typeset_demo_tasks()
    -- build demo pdf here
    return 0
end

kpse.set_program_name("kpsewhich")
if not release_date then
    dofile(kpse.lookup("l3build.lua"))
end
```

The demo PDFs are correctly built via `typeset_demo_tasks`, but are not included in the final zipfile. Is a main documentation required here?

**Comment by josephwright** [comment]
I'm not quite sure I follow what you are up to: are the PDFs pre-built? I'd expect the demos to be included in `typesetfiles`: there is no need for them to be 'the main documentation'. The PDFs will then be copied automatically from `docfiledir` to the TDS, _etc._

Perhaps you could link to the sources, or give an  ASCII-art model of the layout?

**Comment by louisstuart96** [comment]
The pre-build process in `typeset_demo_tasks` is like that of `beamer`: A `tex` file is typeset repeatedly with different parameters, generating several PDFs; The `typesetfiles` is empty, so nothing is typeset **after the pre-build process**.

**Comment by josephwright** [comment]
@louisstuart96 Those are files to typeset to _support_ the main documentation: the individual PDFs don't go into the distribution tree. That's what the `typeset_demo_files` hook is for. Only PDFs that match base names in `typesetfiles` get copied to the distribution tree.

**Comment by wspr** [comment]
Would it work to have something like `docfiles = {"demo-*.pdf"}` ?

**Comment by louisstuart96** [comment]
@wspr It won't work. The code in `copyctan()` says:
```lua
  -- l3build-ctan.lua, lines 51-54
  for _,tab in pairs(
    {bibfiles,demofiles,docfiles,pdffiles,scriptmanfiles,typesetlist}) do
    copyfiles(tab,docfiledir)
  end
```
From this piece of code, all the available files in these lists should be included to the zip files. @josephwright Is there any restrictions in the underlying functions like `cp` or `tree`?

**Comment by josephwright** [comment]
@louisstuart96 The core file functions are not restricted.

I'm still not sure why you can't use `docfiles` for your sources.

**Comment by josephwright** [comment]
Did you get this sorted?

**Comment by louisstuart96** [comment]
@josephwright not yet, but it's well for me to close this.
