### ISSUE TITLE
Support for spaces in directories

### ISSUE THREAD

**Issue by josephwright** [latex3/l3build#76]
As detailed in https://tex.stackexchange.com/questions/456643/l3build-in-directories-that-have-spaces-in-their-names, spaces in directories can be an issue. That case can be covered by adding quotes to the value of `localdir` in the `unpack()` function, but more widely there is likely to be an issue. Probably we need a completely general 'quote./escape the directory' function, to be applied to *every* use of a directory.

**Comment by josephwright** [comment]
An initial sketch of a fix:

- Add a function to escape directory names: on Windows, that works much like the code for LuaTeX (adding quotes), on Unix it needs to replace spaces be escaped spaces
- Apply this to all of the user `...dir` variables just after they are loaded
- Apply this in the `abspath()` function

That should avoid needing to find *every* case where a directory is involved, as they'll all be sorted up-front.

**Comment by leingang** [comment]
I installed this 2018-10-25 release, and the error that I initially reported is gone.  Thank you! However, I have a new issue: the install directory has gotten mangled:

```
$ kpsewhich -var-value TEXMFHOME
/Users/matthew/Library/texmf
$ l3build install
[...]
...18/texmf-dist/scripts/l3build/l3build-file-functions.lua:271: cannot open /Users/matthew/\ ibrary/texmf/tex/latex/mypkg: No such file or directory
```

It appears the `L` in `Library` got substituted to `\ `.

**Comment by josephwright** [comment]
@leingang Should be fixed now: I'll release to CTAN probably tomorrow.

**Comment by leingang** [comment]
Finally installed the updated version.  Works for me now.  Thank you!
