### ISSUE TITLE
white space at start of lines

### ISSUE THREAD

**Issue by davidcarlisle** [latex3/l3build#78]
due to different lengths of file paths the log can get irregular line breaking before page counts or `(..0` file input markers. After existing normalization this means that  the  `[3]` may appear at start of the line, or offset by one space for the same input on different machines.

One approach would be to remove all white space at the start of the line, but that might mask some difference that you want to test so this removes one space if a start pf line begins with spaces followed by [ or (

Change to l3build-check as follows
```

    -- Deal with the fact that "(.aux)" may have still a leading space
--    line = gsub(line, "^ %(%.aux%)", "(.aux)")
    -- remove one space at start of line before ( or [
    line = gsub(line, "^ ( *[%[%(])", "%1")
```

the commented out line is anyway wrong now as it dates to an earlier version when the test name was removed leaving `(.aux)`

**Comment by davidcarlisle** [comment]
actually they are just the most likely thing, but as the log has a newline
if the terminal output wraps for any reason, there is no need to be too
specific, actually removing all white space at the start of a line may yet
be the best course of action.  The restriction to white space then ( or [
just a pragmatic compromise that was enough not to change too many tlg but
fix the ones where issues arose (in ~100 test files on the oberdiek bundle)

**Comment by josephwright** [comment]
@blefloch We used to simply strip out all whitespace at line starts, but it was problematic, largely as it messes up line wrapping.
