### ISSUE TITLE
Add documentation for `upload`

### ISSUE THREAD

**Issue by wspr** [latex3/l3build#79]
Currently the branch in `ctan-post` is set up to use the table `uploaddata` to populate the information needed. The l3build target is `l3build upload`.

Documentation around the fields and an example configuration needs to be added to the main l3build documentation as well as command line help.

**Comment by josephwright** [comment]
I guess once this is done you'll merge the branch and release?

**Comment by wspr** [comment]
Yep. I’m writing documentation now but need to sleep so won’t merge tonight :)
