### ISSUE TITLE
Strange pdf output generated by build system

### ISSUE THREAD

**Issue by TeXtnik** [latex3/l3build#80]
I have a test based on pdf using xelatex. The `tpf` file generated by the 
build system is not rendered fine by evince. The pdf obtained just by running xelatex on the test file looks fine. 
May this be due to the "normalization' process? Can it be somehow dissabled so, a visual inspection can be done before saving the `tpf`? 

(I have to rename the `tpf` file to be able to upload)

The test file is just

```
\input{regression-test}
\PassOptionsToPackage{noinfo}{crop}
\documentclass[CPE,interior]{sbmbook}


\begin{document}

\input{test-book-interior-sample}

\end{document}
```

[test-cpe-example.log](https://github.com/latex3/l3build/files/2667290/test-cpe-example.log)
[test-cpe-example.pdf](https://github.com/latex3/l3build/files/2667291/test-cpe-example.pdf)
[test-cpe-example-tpf.pdf](https://github.com/latex3/l3build/files/2667309/test-cpe-example-tpf.pdf)

**Comment by josephwright** [comment]
The `.tpf` file is a _modified_ PDF to allow binary comparison. If you want to look at the PDF, you'll need to check in the build area.

**Comment by TeXtnik** [comment]
Ok. In the build area, it looks ok. I think we can close this. Probably, some clarification can be added to the docs.
