### ISSUE TITLE
gglo.ist and gind.ist in makeindex/latex in latex-base.tds.zip please

### ISSUE THREAD

**Issue by kberry** [latex3/l3build#81]
instead of being directly inside makeindex/. thanks.

**Comment by josephwright** [comment]
Moving to `l3build`: it's an issue there if anywhere.

**Comment by josephwright** [comment]
I see the issue: for BibTeX, `base` is 'us' so a bit of manipulation, but for MakeIndex it isn't (we want `latex`). I'll have to adjust the special-casing code for 'tools' installation. May take a day or so ...

**Comment by kberry** [comment]
there is no hurry. i already installed the new latex2e release. thanks.

**Comment by josephwright** [comment]
Should be sorted by 84b61e0d73de3eb458361717f3616b61857876f0.
