### ISSUE TITLE
extend engines/format options

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#84]
So that it doesn't get lost:

I would like to be able to run l3build tests with luatex53 and with the new luahbtex. 

For this I need some interface to setup more testing engines/formats in config files. It would be quite okay for me  to define the concrete calls explicitly in the build.lua, e.g. as 

~~~~
formats["latex"]["luatex53"]= "luatex53 --fmt=lualatex53"
formats["latex"]["luahbtex"]= "luahblatex"
....
~~~~

**Comment by josephwright** [comment]
Hopefully this is now working: `specialformats` will allow you to do more-or-less whatever you want. We may still need to extend it a bit: I've left a couple of special case things in (XeTeX/no-PDF and ConTeXt's jobname handling).
