### ISSUE TITLE
Make "l3build tag" update copyright

### ISSUE THREAD

**Issue by blefloch** [latex3/l3build#86]
Before each release of LaTeX3, Joseph runs `l3build tag`.  It would be neat if this also updated the copyright of every file that is edited by `l3build tag`.  For the year 2019 I would use the following three regex replacements one after the other.  Not sure how to translate this to Lua's patterns.
```
"^(Copyright.*\d\d\d\d)([^\d]*)$" -> "\1,2019\2"
"-2018,2019" -> "-2019"
"2017,2018,2019" -> "2017-2019"
```

**Comment by josephwright** [comment]
Do we want a separate target or is this 'part of tagging'/'part of release'?

**Comment by blefloch** [comment]
I was thinking of this as part of tagging.

**Comment by josephwright** [comment]
As part of tagging, one just has to adjust the `update_tag()` function, which is something I've not pre-defined (simply too many possible approaches). So we can add the suggestion to our own build scripts rather than needing to adjust `l3build`.

**Comment by josephwright** [comment]
I've added this to our own scripts. I'm not sure it can truly be generalised. If it can, the same applies to tagging itself.

**Comment by wspr** [comment]
FWIW I agree this should all happen as part of a single `l3build tag` process that is customisable by the user.

Really the only improvement we could make is to provide some templates around how we think copyright statements should be constructed and include example code for updating it. I don’t think we could provide a general interface.
