### ISSUE TITLE
support setting epoch on documentation builds.

### ISSUE THREAD

**Issue by openmath-travis** [latex3/l3build#9]
Currently (on tl 2016 and 2017) we allow the epoch date to be set to produce reproducible PDF for testing,

It would be good to have an option to also set it for documentation.

One possible use for this:

With continuous integration, when an edit of a readme file triggers travis-ci to regenerate everything  you don't end up committing a load of spurious changes to the gh-pages
website (well you still commit but nothing happens)

**Comment by josephwright** [comment]
I'm guessing this is @davidcarlisle in disguise :)

Presumably such a feature would want the possibility of an  epoch setting separate from the testing one: split `epoch` into `testepoch` and `docepoch`, perhaps?

**Comment by davidcarlisle** [comment]
yes sorry didn't spot that it picked up an existing login.
yes separate settings for doc and testing would be good I think.

**Comment by josephwright** [comment]
Notwithstanding any worries about 'faking' the meta-data, presumably one might want to set the epoch at the command line, for example to allow picking a 'marker' time for the production of PDFs ('All releases are a 09:00 am' or whatever). That suggests a logic

- Variable for the epoch itself
- Flag to apply the epoch to doc building, `false` as standard
- Flag to apply the epoch to tests, `true` as standard
- Option (`-e`?) to pass the epoch from the command line

This may avoid needing two versions of the epoch, one for tests and one for docs: perhaps the two are still required under such a scheme?

**Comment by davidcarlisle** [comment]
yes I doubt you would often (ever) need two separate dates so just having the two flags plus a date variable is probably enough. Even the command line option is possibly more than is needed as so long as you can set the flags so lua doesn't set the environment variable you could always just set it on the command line anyway so

```
SOURCE_DATE_EPOCH=1498228223 FORCE_SOURCE_DATE=1 texlua build.lua
```

**Comment by josephwright** [comment]
@davidcarlisle  Could you take a look at my suggestion (a 'feature branch'!)?

**Comment by josephwright** [comment]
BTW, at present we use the 'raw' epoch value here: would a string using something 'human readable' be better?

**Comment by davidcarlisle** [comment]
do you mean human readable user input argument or human readable metadata date (don't you have to pass in a numeric epoch?)  as input argument it would be nicer to be able to say 2017-06-29 but does lua have enough built in date handling to convert?

Oh it does, you should be able to do https://www.lua.org/pil/22.1.html

`print(os.time{year=1970, month=1, day=1, hour=0})`

to get 

$ texlua d.lua
-3600

which seems strangely affected by current timezone, although that is apparently as specified in the above which shows results for Rio...  I suppose that makes sort of sense but a way to fix UTC input would be better here

**Comment by josephwright** [comment]
Taking 'human' data is probably a better plan than using an epoch value, but I wonder how that would look at the command line:
```
texlua build.lua check -d 2017-06-29 -t 09:00:00 -E
```
perhaps?

**Comment by FrankMittelbach** [comment]
perhaps.

maybe with also a few supported keywords like "now" for setting day and 
time and "today" for setting the date perhaps with a default time of 
00:00:00 or something along those lines

**Comment by josephwright** [comment]
@FrankMittelbach  In the above 'now' would be just
```
texlua build.lua check -E
```
I think: force epoch from the command line => over-ride any setting in `build.lua`.

**Comment by josephwright** [comment]
@davidcarlisle  Suggests that at least initially time isn't a big issue: pick a fixed one and go with date only (most people won't need to worry about the time, just have a 'known' value).

**Comment by openmath-travis** [comment]
if we want to add time as well (which could be added later) I wouldn't add
extra arguments just support a longer iso datetime string so you could
input the output of

$ date --iso-8601=ns
2017-06-29T22:36:39,930829600+01:00

or more or less any substring of that.

for similar reasons I'd support a numeric epoch number or a date (or
datetime)  as values for the same argument

**Comment by josephwright** [comment]
@davidcarlisle (In disguise) Remember I'm a Windows person: `date` and `time` are separate things to me ;) Certainly if they can be combined this is good.

**Comment by josephwright** [comment]
I'll come up with a v2 proposal tomorrow.

**Comment by josephwright** [comment]
Thinking some more, the epoch may or may not look like a date. So probably we do want to stick with `-E <epoch>`, and inside `l3build` take that or the `epoch` setting and re-format as-required into a Unix EPOCH. @davidcarlisle  suggested elsewhere
```lua



function setepoch (s)
  local y,m,d
   y,m,d = string.match(s,"^(%d%d%d%d)-(%d%d)-(%d%d)$")
  if y then
  return os.time{year=y, month=m, day=d, hour=0,sec=0,isdst=nil} -
  os.time{year=1970, month=1, day=1, hour=0,sec=0,isdst=nil}
  else if string.match(s,"^%d+$") then
     return tonumber(s)
  else
     return 0
  end
  end
  end
```
which could happily go as a one-shot just after `argparse` work: pick up either the normal `epoch` or the `-E` argument and reformat if required, then apply if `force<thing>epoch` is true or if `-E` applies.

Code coming up later on.

**Comment by josephwright** [comment]
@FrankMittelbach Happy(ish) with this?

**Comment by FrankMittelbach** [comment]
assuming that I understood it correctly , yes I guess so :-)
