### ISSUE TITLE
pdf-based tests on the latex+dvips +ps2pdf route

### ISSUE THREAD

**Issue by u-fischer** [latex3/l3build#94]
In view of the work on pdf resources it would be nice to be able to run pdf-based tests also with 

~~~~
latex
dvips
ps2pdf -dCompressStreams=false -dCompressPages=false -dNOSAFER
~~~~

(the -dNOSAFER is optional for transparency). 

As regression-test assumes dvipdfmx when output mode is 0, currently it isn't even possible to run test files manually for inspection, dvips then complains 
`dvips.exe: Unknown keyword (pdf:) in \special will be ignored` )

**Comment by josephwright** [comment]
Presumably we need to go down the same route as `expl3`: assume `dvips` for LaTeX, `dvipdfmx` for (u)pLaTeX. So the question is how to switch: the idea of a pre-set constant I guess.

**Comment by u-fischer** [comment]
for regression-test using dvips as default is probably sensible, I don't see the need for many tests with latex+dvipdfmx. But some test for a `\c_sys_backend_tl`  would be okay too. The main question is imho how to setup and declare the check engine.

**Comment by u-fischer** [comment]
latex+dvips+ps2pdf tests works now.
