### ISSUE TITLE
typeset target does not like & in directories

### ISSUE THREAD

**Issue by schtandard** [latex3/l3build#95]
The behavior addressed in https://github.com/latex3/l3build/issues/91 also occurs when the directory path contains the symbol `&` (instead of spaces as in the linked issue).

That is, placing the three attached files (after removing `.txt`) into `d:/test&co/` and running `l3build doc`, compilation fails with the error message
```
! LaTeX Error: File `testpackage.sty' not found.
```

----

Files:
[testpackage.dtx.txt](https://github.com/latex3/l3build/files/3365509/testpackage.dtx.txt)
[testpackage.ins.txt](https://github.com/latex3/l3build/files/3365510/testpackage.ins.txt)
[build.lua.txt](https://github.com/latex3/l3build/files/3365511/build.lua.txt)

----

(I am using a current version of MiKTeX on Windows 10.)

**Comment by josephwright** [comment]
Well the reason is reasonably clear: `&` is a special character in the Windows command line. The question is whether this should be supported, I guess: it's something I'd not recommend, but as Microsoft have never been that clear about such things, I support I should look to sort it.

**Comment by josephwright** [comment]
I know it's a 'reverse dupe', but I'm going to look at this in https://github.com/latex3/l3build/issues/124 - we want a single place to handle 'escaping characters'.
