### ISSUE TITLE
.tlg file : version number scheme

### ISSUE THREAD

**Issue by maieul** [latex3/l3build#96]
Consider this .tlg file
https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L1185

We have still in the normalized log a partial version number (.3). That is because, for reledmac/reledmac, I use a
`x.y.z` version number schema, and not a `x.y` schema. Furthermore, I can use `x.y.z<letter>` schema.

should it be possible to extend the test to normalize the version number in the log. 

Also some line problematic :
- https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L40
-  https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L40
- https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L342
- https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L1042
- https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L1074
- https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L1076
- https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L1179
- https://github.com/maieul/ledmac/blob/bbd3664/testfiles-allengines-2/1-verses.luatex.tlg#L1193

**Comment by josephwright** [comment]
Ah yes, we do have some normalisation for version strings in date lines

I wonder if I should make the normalisation here a function rather than try to guess everyone's versioning approach? Or I could have a simple `versionpattern`  variable?

**Comment by FrankMittelbach** [comment]
I would prefer a variable over a function ... a function is an extra hurdle for some people (if they don#t speak "lua")

**Comment by josephwright** [comment]
@FrankMittelbach  Sure, that's what I was thinking too. Also makes the change would be easier for me: I just replace a string literal by a variable.

**Comment by stone-zeng** [comment]
`ctex` bundle also uses the `x.x.x` pattern, so please consider to add this feature if possible. Thank you!

**Comment by zepinglee** [comment]
[Semantic Versioning](https://semver.org/) (SemVer, `x.x.x`) is a well-defined scheme and it's adopted in a wide variety of software packages. In the most up-to-date TeX Live distribution, there are still 579 out of 3436 packages (detailed below) that use SemVer. The current `l3build` normalizes `v0.4.3` to `v....3` which needs to be updated in every patch version. It would be helpful to normalize SemVer in `l3build`.

I suggest adding `line = gsub(line,"v%d+%.%d+%.%d+[%d%a.+%-]*","v...")` into the following lines.
https://github.com/latex3/l3build/blob/d7e58d9ce7ef53fad61a7c22e513cf7d34342238/l3build-check.lua#L171-L175

The counting of packages is done via searching in `texlive.tlpdb` with the following regex which is available at the bottom of page <https://semver.org/>. 3436 is the number of packages with `catalogue-version`.
```
^catalogue-version (0|[1-9]\d*)\.(0|[1-9]\d*)\.(0|[1-9]\d*)(?:-((?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*)(?:\.(?:0|[1-9]\d*|\d*[a-zA-Z-][0-9a-zA-Z-]*))*))?(?:\+([0-9a-zA-Z-]+(?:\.[0-9a-zA-Z-]+)*))?$
```

**Comment by josephwright** [comment]
@zepinglee No issue at all with making an adjustment, but I'm not sure I understand

> I suggest adding `line = gsub(line,"v%d+%.%d+%.%d+[%d%a.+%-]*","v...")` into the following lines.

Wouldn't `"v%d+%.%d+%.%d+"` be the correct match for a semantic version line?

**Comment by zepinglee** [comment]
> Wouldn't `"v%d+%.%d+%.%d+"` be the correct match for a semantic version line?

SemVer allows version number optionally followed by a pre-release version (e.g., `1.0.0-alpha.1`) and build metadata (`1.0.0-beta+exp.sha.5114f85`). Both of the additional version parts are identifiers separated by dots. There are 6 packages with pre-release versions in the current tlpdb.

Additionally, I just find `%w` character class in Lua doesn't include underscore (`_`) and thus it's safe to replace `%d%a` with `%w`.

**Comment by josephwright** [comment]
@zepinglee  OK, whilst I think that it's pretty unlikely strings of that form will pop up, but I think we are safe enough adding the suggestion.

**Comment by josephwright** [comment]
I think we dealt with this ...
